/**
 * 工作流接口文档
 * 工作流接口文档
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.chinacreator.c2.flow.rest.api;

import com.chinacreator.c2.flow.rest.ApiException;
import java.util.Date;
import com.chinacreator.c2.flow.rest.model.PageListResponseWfHistoricTaskInstanceResponse;
import com.chinacreator.c2.flow.rest.model.WfHistoricIdentityLinkResponse;
import com.chinacreator.c2.flow.rest.model.WfHistoricTaskInstanceResponse;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for HistoryTaskApi
 */
public class HistoryTaskApiTest {

    private final HistoryTaskApi api = new HistoryTaskApi();

    
    /**
     * 获取历史任务列表
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getHistoricTaskProcessInstancesTest() throws ApiException {
        String taskId = null;
        String processInstanceId = null;
        String processBusinessKey = null;
        String processDefinitionKey = null;
        String processDefinitionId = null;
        String processDefinitionName = null;
        String executionId = null;
        String taskName = null;
        String taskNameLike = null;
        String taskDescription = null;
        String taskDescriptionLike = null;
        String taskDefinitionKey = null;
        String taskDeleteReason = null;
        String taskDeleteReasonLike = null;
        String taskAssignee = null;
        String taskAssigneeLike = null;
        String taskOwner = null;
        String taskOwnerLike = null;
        String taskInvolvedUser = null;
        Integer taskPriority = null;
        Boolean finished = null;
        Boolean processFinished = null;
        String parentTaskId = null;
        Date dueDate = null;
        Date dueDateBefore = null;
        Date dueDateAfter = null;
        Date taskCreatedOn = null;
        Date taskCreatedBefore = null;
        Date taskCreatedAfter = null;
        Date taskCompletedOn = null;
        Date taskCompletedBefore = null;
        Date taskCompletedAfter = null;
        Boolean includeTaskLocalVariables = null;
        Boolean includeProcessVariables = null;
        String tenantId = null;
        String tenantIdLike = null;
        Boolean withoutTenantId = null;
        // PageListResponseWfHistoricTaskInstanceResponse response = api.getHistoricTaskProcessInstances(taskId, processInstanceId, processBusinessKey, processDefinitionKey, processDefinitionId, processDefinitionName, executionId, taskName, taskNameLike, taskDescription, taskDescriptionLike, taskDefinitionKey, taskDeleteReason, taskDeleteReasonLike, taskAssignee, taskAssigneeLike, taskOwner, taskOwnerLike, taskInvolvedUser, taskPriority, finished, processFinished, parentTaskId, dueDate, dueDateBefore, dueDateAfter, taskCreatedOn, taskCreatedBefore, taskCreatedAfter, taskCompletedOn, taskCompletedBefore, taskCompletedAfter, includeTaskLocalVariables, includeProcessVariables, tenantId, tenantIdLike, withoutTenantId);

        // TODO: test validations
    }
    
    /**
     * 获取历史任务候选人或组信息
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getHistoryTaskIdentityLinksTest() throws ApiException {
        String taskId = null;
        // List<WfHistoricIdentityLinkResponse> response = api.getHistoryTaskIdentityLinks(taskId);

        // TODO: test validations
    }
    
    /**
     * 获取历史任务信息
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTaskInstanceTest() throws ApiException {
        String taskId = null;
        Boolean includeTaskLocalVariables = null;
        Boolean includeProcessVariables = null;
        // WfHistoricTaskInstanceResponse response = api.getTaskInstance(taskId, includeTaskLocalVariables, includeProcessVariables);

        // TODO: test validations
    }
    
}
