/**
 * 工作流接口文档
 * 工作流接口文档
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.chinacreator.c2.flow.rest.api;

import com.chinacreator.c2.flow.rest.ApiException;
import com.chinacreator.c2.flow.rest.model.WfHistoricIdentityLinkResponse;
import com.chinacreator.c2.flow.rest.model.PageListResponseWfHistoricProcessInstanceResponse;
import java.util.Date;
import com.chinacreator.c2.flow.rest.model.WfCommentResponse;
import com.chinacreator.c2.flow.rest.model.WfHistoricProcessInstanceResponse;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for HistoryInstanceApi
 */
public class HistoryInstanceApiTest {

    private final HistoryInstanceApi api = new HistoryInstanceApi();

    
    /**
     * 获取历史流程实例候选人和组信息
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getHistoricInstanceIdentityLinksTest() throws ApiException {
        String processInstanceId = null;
        // List<WfHistoricIdentityLinkResponse> response = api.getHistoricInstanceIdentityLinks(processInstanceId);

        // TODO: test validations
    }
    
    /**
     * 获取历史工作流实例列表
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getHistoricProcessInstancesTest() throws ApiException {
        String processInstanceId = null;
        String processDefinitionKey = null;
        String processDefinitionId = null;
        String businessKey = null;
        String involvedUser = null;
        Boolean finished = null;
        String superProcessInstanceId = null;
        Boolean excludeSubprocesses = null;
        Date finishedBefore = null;
        Date finishedAfter = null;
        Date startedBefore = null;
        Date startedAfter = null;
        String startedBy = null;
        Boolean includeProcessVariables = null;
        String tenantId = null;
        String tenantIdLike = null;
        Boolean withoutTenantId = null;
        // PageListResponseWfHistoricProcessInstanceResponse response = api.getHistoricProcessInstances(processInstanceId, processDefinitionKey, processDefinitionId, businessKey, involvedUser, finished, superProcessInstanceId, excludeSubprocesses, finishedBefore, finishedAfter, startedBefore, startedAfter, startedBy, includeProcessVariables, tenantId, tenantIdLike, withoutTenantId);

        // TODO: test validations
    }
    
    /**
     * 获取历史流程实例评论意见信息
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getHistoryInstanceCommentsTest() throws ApiException {
        String processInstanceId = null;
        // List<WfCommentResponse> response = api.getHistoryInstanceComments(processInstanceId);

        // TODO: test validations
    }
    
    /**
     * 获取历史流程实例信息
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getHistoryProcessInstanceTest() throws ApiException {
        String processInstanceId = null;
        // WfHistoricProcessInstanceResponse response = api.getHistoryProcessInstance(processInstanceId);

        // TODO: test validations
    }
    
    /**
     * 获取流程实例图
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getHistoryProcessInstanceDiagramTest() throws ApiException {
        String processInstanceId = null;
        // api.getHistoryProcessInstanceDiagram(processInstanceId);

        // TODO: test validations
    }
    
}
