/**
 * 工作流接口文档
 * 工作流接口文档
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.chinacreator.c2.flow.rest.api;

import com.chinacreator.c2.flow.rest.ApiException;
import com.chinacreator.c2.flow.rest.model.PageListResponseWfHistoricProcessInstanceResponse;
import com.chinacreator.c2.flow.rest.model.WfHistoricProcessInstanceQueryRequest;
import com.chinacreator.c2.flow.rest.model.PageListResponseWfHistoricTaskInstanceResponse;
import com.chinacreator.c2.flow.rest.model.WfHistoricTaskInstanceQueryRequest;
import com.chinacreator.c2.flow.rest.model.PageListResponseWfProcessInstanceResponse;
import com.chinacreator.c2.flow.rest.model.WfProcessInstanceQueryRequest;
import com.chinacreator.c2.flow.rest.model.PageListResponseWfTaskResponse;
import com.chinacreator.c2.flow.rest.model.WfTaskQueryRequest;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for QueryApi
 */
public class QueryApiTest {

    private final QueryApi api = new QueryApi();

    
    /**
     * 查询历史流程实例列表
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void queryHistoricProcessInstancesTest() throws ApiException {
        WfHistoricProcessInstanceQueryRequest body = null;
        // PageListResponseWfHistoricProcessInstanceResponse response = api.queryHistoricProcessInstances(body);

        // TODO: test validations
    }
    
    /**
     * 查询历史任务列表
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void queryHistoricTaskInstancesTest() throws ApiException {
        WfHistoricTaskInstanceQueryRequest body = null;
        // PageListResponseWfHistoricTaskInstanceResponse response = api.queryHistoricTaskInstances(body);

        // TODO: test validations
    }
    
    /**
     * 查询流程实例列表
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void queryProcessInstancesTest() throws ApiException {
        WfProcessInstanceQueryRequest body = null;
        // PageListResponseWfProcessInstanceResponse response = api.queryProcessInstances(body);

        // TODO: test validations
    }
    
    /**
     * 查询待办列表
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void queryTasksTest() throws ApiException {
        WfTaskQueryRequest body = null;
        // PageListResponseWfTaskResponse response = api.queryTasks(body);

        // TODO: test validations
    }
    
}
