/**
 * 工作流接口文档
 * 工作流接口文档
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.chinacreator.c2.flow.rest.api;

import org.junit.Assert;
import org.junit.Test;

import com.chinacreator.c2.flow.rest.ApiException;
import com.chinacreator.c2.flow.rest.model.PageListResponseWfHistoricProcessInstanceResponse;
import com.chinacreator.c2.flow.rest.model.PageListResponseWfHistoricTaskInstanceResponse;
import com.chinacreator.c2.flow.rest.model.PageListResponseWfProcessInstanceResponse;
import com.chinacreator.c2.flow.rest.model.PageListResponseWfTaskResponse;
import com.chinacreator.c2.flow.rest.model.WfHistoricProcessInstanceQueryRequest;
import com.chinacreator.c2.flow.rest.model.WfHistoricTaskInstanceQueryRequest;
import com.chinacreator.c2.flow.rest.model.WfProcessInstanceQueryRequest;
import com.chinacreator.c2.flow.rest.model.WfTaskQueryRequest;

/**
 * API tests for QueryApi
 */
public class QueryApiTest {
	
    private final QueryApi api = new QueryApi();
    
    /**
     * 查询历史流程实例列表
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void queryHistoricProcessInstancesTest() throws ApiException {
        WfHistoricProcessInstanceQueryRequest body = new WfHistoricProcessInstanceQueryRequest();
        PageListResponseWfHistoricProcessInstanceResponse response = api.queryHistoricProcessInstances(body);
        Assert.assertNotNull("not null",response);
    }
    
    /**
     * 查询历史任务列表
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void queryHistoricTaskInstancesTest() throws ApiException {
        WfHistoricTaskInstanceQueryRequest body = new WfHistoricTaskInstanceQueryRequest();
        body.setStart(0);
        body.setSize(10);
        body.setFinished(null);
        System.out.println(body.toString());
        PageListResponseWfHistoricTaskInstanceResponse response = api.queryHistoricTaskInstances(body);
        Assert.assertNotNull("not null",response);
    }
    
    /**
     * 查询流程实例列表
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void queryProcessInstancesTest() throws ApiException {
        WfProcessInstanceQueryRequest body = new WfProcessInstanceQueryRequest();
        PageListResponseWfProcessInstanceResponse response = api.queryProcessInstances(body);
        Assert.assertNotNull("not null",response);
    }
    
    
    /**
     * 查询待办列表
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void queryTasksTest() throws ApiException {
        WfTaskQueryRequest body = new WfTaskQueryRequest();
		PageListResponseWfTaskResponse result = api.queryTasks(body);
		Assert.assertNotNull("not null",result);
    }
    
}
