/**
 * 工作流接口文档
 * 工作流接口文档
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.chinacreator.c2.flow.rest.api;

import com.chinacreator.c2.flow.rest.ApiException;
import com.chinacreator.c2.flow.rest.model.WfDeploymentResponse;
import com.chinacreator.c2.flow.rest.model.WfDeploymentResourceResponse;
import com.chinacreator.c2.flow.rest.model.PageListResponseWfDeploymentResponse;
import com.chinacreator.c2.flow.rest.model.WfDeploymentRequest;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for RepositoryDeploymentApi
 */
public class RepositoryDeploymentApiTest {

    private final RepositoryDeploymentApi api = new RepositoryDeploymentApi();

    
    /**
     * 删除流程部署
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteDeploymentTest() throws ApiException {
        String deploymentId = null;
        // api.deleteDeployment(deploymentId);

        // TODO: test validations
    }
    
    /**
     * 获取部署信息)
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getDeploymentTest() throws ApiException {
        String deploymentId = null;
        // WfDeploymentResponse response = api.getDeployment(deploymentId);

        // TODO: test validations
    }
    
    /**
     * 获取部署下的某个资源信息)
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getDeploymentResourceTest() throws ApiException {
        String deploymentId = null;
        String resourceId = null;
        // WfDeploymentResourceResponse response = api.getDeploymentResource(deploymentId, resourceId);

        // TODO: test validations
    }
    
    /**
     * 下载部署下的资源数据)
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getDeploymentResourceDataTest() throws ApiException {
        String deploymentId = null;
        String resourceId = null;
        // byte[] response = api.getDeploymentResourceData(deploymentId, resourceId);

        // TODO: test validations
    }
    
    /**
     * 获取部署下的资源列表)
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getDeploymentResourcesTest() throws ApiException {
        String deploymentId = null;
        // List<WfDeploymentResourceResponse> response = api.getDeploymentResources(deploymentId);

        // TODO: test validations
    }
    
    /**
     * 获取流程定义部署列表
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getDeploymentsTest() throws ApiException {
        String name = null;
        String nameLike = null;
        String category = null;
        String categoryNotEquals = null;
        String tenantId = null;
        String tenantIdLike = null;
        Boolean withoutTenantId = null;
        // PageListResponseWfDeploymentResponse response = api.getDeployments(name, nameLike, category, categoryNotEquals, tenantId, tenantIdLike, withoutTenantId);

        // TODO: test validations
    }
    
    /**
     * 部署流程定义资源(*bpmn20.xml)
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void uploadDeploymentTest() throws ApiException {
        WfDeploymentRequest body = null;
        // WfDeploymentResponse response = api.uploadDeployment(body);

        // TODO: test validations
    }
    
}
