/**
 * 工作流接口文档
 * 工作流接口文档
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.chinacreator.c2.flow.rest.api;

import org.junit.Test;

import com.chinacreator.c2.flow.rest.ApiException;
import com.chinacreator.c2.flow.rest.model.PageListResponseWfProcessInstanceResponse;
import com.chinacreator.c2.flow.rest.model.WfJumpRequest;
import com.chinacreator.c2.flow.rest.model.WfProcessInstanceActionRequest;
import com.chinacreator.c2.flow.rest.model.WfProcessInstanceCreateRequest;
import com.chinacreator.c2.flow.rest.model.WfProcessInstanceResponse;
import com.chinacreator.c2.flow.rest.model.WfRestVariable;

/**
 * API tests for RuntimeInstanceApi
 */
public class RuntimeInstanceApiTest {
	

    private final RuntimeInstanceApi api = new RuntimeInstanceApi();
    
    private static String processInstanceId=null;

    
    /**
     * 启动工作流实例
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createProcessInstanceTest() throws ApiException {
        WfProcessInstanceCreateRequest body = new WfProcessInstanceCreateRequest();
        body.setProcessDefinitionKey("jtest");
        WfRestVariable wfRestVariable=new WfRestVariable();
        wfRestVariable.setName("userId");
        wfRestVariable.setType(WfRestVariable.TypeEnum.STRING);
        wfRestVariable.setValue("test_user");
        wfRestVariable.setVariableScope(WfRestVariable.VariableScopeEnum.GLOBAL);
        body.addVariablesItem(wfRestVariable);
        WfProcessInstanceResponse response = api.createProcessInstance(body);
        processInstanceId=response.getId();
    }
    
    
    /**
     * 获取工作流实例信息
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getProcessInstanceTest() throws ApiException {
        WfProcessInstanceResponse response = api.getProcessInstance(processInstanceId);
    }
    
    
    /**
     * 获取流程实例图
     *
     * 获取流程实例图片，红色框标记为当前环节
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getProcessInstanceDiagramTest() throws ApiException {
         api.getProcessInstanceDiagram(processInstanceId);
    }
    
    

    /**
     * 工作流实例列表
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getProcessInstancesTest() throws ApiException {
        String id = null;
        String processDefinitionKey = null;
        String processDefinitionId = null;
        String businessKey = null;
        String involvedUser = null;
        Boolean suspended = null;
        String superProcessInstanceId = null;
        String subProcessInstanceId = null;
        Boolean excludeSubprocesses = null;
        Boolean includeProcessVariables = null;
        String tenantId = null;
        String tenantIdLike = null;
        Boolean withoutTenantId = null;
        String order = null;
        Integer sort = null;
        Integer start = null;
        Integer size = null;
        PageListResponseWfProcessInstanceResponse response = api.getProcessInstances(id, processDefinitionKey, processDefinitionId, businessKey, involvedUser, suspended, superProcessInstanceId, subProcessInstanceId, excludeSubprocesses, includeProcessVariables, tenantId, tenantIdLike, withoutTenantId, order, sort, start, size);

    }
    
    
    /**
     * 自由流
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void goAnyWhereTest() throws ApiException {
        String processInstanceId = null;
        WfJumpRequest body = null;
        // WfActionResult response = api.goAnyWhere(processInstanceId, body);

        // TODO: test validations
    }
    
    /**
     * 激活或挂起工作流实例
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void performProcessInstanceActionTest() throws ApiException {
        WfProcessInstanceActionRequest body = new WfProcessInstanceActionRequest();
        body.setAction(WfProcessInstanceActionRequest.ActionEnum.SUSPEND);
        WfProcessInstanceResponse response = api.performProcessInstanceAction(processInstanceId, body);
        
        
    }
    
    
    /**
     * 删除工作流实例信息
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteProcessInstanceTest() throws ApiException {
        String deleteReason = "junit rest";
        Object response = api.deleteProcessInstance(processInstanceId, deleteReason);
    }
    
}
