/**
 * 工作流接口文档
 * 工作流接口文档
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.chinacreator.c2.flow.rest.api;

import com.chinacreator.c2.flow.rest.ApiException;
import com.chinacreator.c2.flow.rest.model.WfCommentResponse;
import com.chinacreator.c2.flow.rest.model.WfRestVariable;
import com.chinacreator.c2.flow.rest.model.WfTaskActionRequest;
import com.chinacreator.c2.flow.rest.model.WfActionResult;
import com.chinacreator.c2.flow.rest.model.WfTaskResponse;
import com.chinacreator.c2.flow.rest.model.PageListResponseWfTaskResponse;
import java.util.Date;
import com.chinacreator.c2.flow.rest.model.WfTaskRequest;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for RuntimeTaskApi
 */
public class RuntimeTaskApiTest {

    private final RuntimeTaskApi api = new RuntimeTaskApi();

    
    /**
     * 添加任务意见
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createCommentTest() throws ApiException {
        String taskId = null;
        WfCommentResponse body = null;
        // WfCommentResponse response = api.createComment(taskId, body);

        // TODO: test validations
    }
    
    /**
     * 批量添加任务流程变量
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createTaskVariableTest() throws ApiException {
        String taskId = null;
        List<WfRestVariable> body = null;
        // List<WfRestVariable> response = api.createTaskVariable(taskId, body);

        // TODO: test validations
    }
    
    /**
     * 批量删除任务流程变量
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteAllLocalTaskVariablesTest() throws ApiException {
        String taskId = null;
        // api.deleteAllLocalTaskVariables(taskId);

        // TODO: test validations
    }
    
    /**
     * 删了某任务下某条意见
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteCommentTest() throws ApiException {
        String taskId = null;
        String commentId = null;
        // api.deleteComment(taskId, commentId);

        // TODO: test validations
    }
    
    /**
     * 删除任务
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteTaskTest() throws ApiException {
        String taskId = null;
        Boolean cascadeHistory = null;
        String deleteReason = null;
        // api.deleteTask(taskId, cascadeHistory, deleteReason);

        // TODO: test validations
    }
    
    /**
     * 处理任务
     *
     * 处理任务：签收(CLAIM)、签收并完成(CLAIM_COMPLETE)、完成(COMPLETE)、委托代理(DELEGATE)、回绝委托代理(RESOLVE)、退回任务(REJECT)
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void executeTaskActionTest() throws ApiException {
        String taskId = null;
        WfTaskActionRequest body = null;
        // WfActionResult response = api.executeTaskAction(taskId, body);

        // TODO: test validations
    }
    
    /**
     * 获取某任务下某条意见详细
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCommentTest() throws ApiException {
        String taskId = null;
        String commentId = null;
        // WfCommentResponse response = api.getComment(taskId, commentId);

        // TODO: test validations
    }
    
    /**
     * 获取某任务意见列表
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCommentsTest() throws ApiException {
        String taskId = null;
        // List<WfCommentResponse> response = api.getComments(taskId);

        // TODO: test validations
    }
    
    /**
     * 获取任务信息
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTaskTest() throws ApiException {
        String taskId = null;
        Boolean includeTaskLocalVariables = null;
        Boolean includeProcessVariables = null;
        // WfTaskResponse response = api.getTask(taskId, includeTaskLocalVariables, includeProcessVariables);

        // TODO: test validations
    }
    
    /**
     * 待办列表
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTasksTest() throws ApiException {
        String name = null;
        String nameLike = null;
        String description = null;
        String descriptionLike = null;
        Integer priority = null;
        Integer minimumPriority = null;
        Integer maximumPriority = null;
        String assignee = null;
        String owner = null;
        Boolean unassigned = null;
        String delegationState = null;
        String candidateUser = null;
        String involvedUser = null;
        String candidateGroup = null;
        String processDefinitionKey = null;
        String processDefinitionKeyLike = null;
        String processDefinitionName = null;
        String processDefinitionNameLike = null;
        String processInstanceId = null;
        String processInstanceBusinessKey = null;
        String executionId = null;
        Date createdOn = null;
        Date createdBefore = null;
        Date createdAfter = null;
        Boolean excludeSubTasks = null;
        String taskDefinitionKey = null;
        String taskDefinitionKeyLike = null;
        Date dueDate = null;
        Date dueBefore = null;
        Date dueAfter = null;
        Boolean active = null;
        Boolean includeTaskLocalVariables = null;
        Boolean includeProcessVariables = null;
        String tenantId = null;
        String tenantIdLike = null;
        Boolean withoutTenantId = null;
        // PageListResponseWfTaskResponse response = api.getTasks(name, nameLike, description, descriptionLike, priority, minimumPriority, maximumPriority, assignee, owner, unassigned, delegationState, candidateUser, involvedUser, candidateGroup, processDefinitionKey, processDefinitionKeyLike, processDefinitionName, processDefinitionNameLike, processInstanceId, processInstanceBusinessKey, executionId, createdOn, createdBefore, createdAfter, excludeSubTasks, taskDefinitionKey, taskDefinitionKeyLike, dueDate, dueBefore, dueAfter, active, includeTaskLocalVariables, includeProcessVariables, tenantId, tenantIdLike, withoutTenantId);

        // TODO: test validations
    }
    
    /**
     * 获取某任务某流程变量
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getVariableTest() throws ApiException {
        String taskId = null;
        String variableName = null;
        String scope = null;
        // WfRestVariable response = api.getVariable(taskId, variableName, scope);

        // TODO: test validations
    }
    
    /**
     * 获取某任务流程变量集合
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getVariablesTest() throws ApiException {
        String taskId = null;
        String scope = null;
        // List<WfRestVariable> response = api.getVariables(taskId, scope);

        // TODO: test validations
    }
    
    /**
     * 修改任务
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateTaskTest() throws ApiException {
        String taskId = null;
        WfTaskRequest body = null;
        // WfTaskResponse response = api.updateTask(taskId, body);

        // TODO: test validations
    }
    
}
