/**
 * 工作流接口文档
 * 工作流接口文档
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.chinacreator.c2.flow.rest.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * 评论意见信息
 */
@ApiModel(description = "评论意见信息")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-12-15T15:13:20.386+08:00")
public class WfCommentResponse   {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("author")
  private String author = null;

  @JsonProperty("message")
  private String message = null;

  public WfCommentResponse id(String id) {
    this.id = id;
    return this;
  }

   /**
   * 意见id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "意见id")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public WfCommentResponse author(String author) {
    this.author = author;
    return this;
  }

   /**
   * 意见作者
   * @return author
  **/
  @ApiModelProperty(example = "null", value = "意见作者")
  public String getAuthor() {
    return author;
  }

  public void setAuthor(String author) {
    this.author = author;
  }

  public WfCommentResponse message(String message) {
    this.message = message;
    return this;
  }

   /**
   * 意见内容
   * @return message
  **/
  @ApiModelProperty(example = "null", value = "意见内容")
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WfCommentResponse wfCommentResponse = (WfCommentResponse) o;
    return Objects.equals(this.id, wfCommentResponse.id) &&
        Objects.equals(this.author, wfCommentResponse.author) &&
        Objects.equals(this.message, wfCommentResponse.message);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, author, message);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WfCommentResponse {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    author: ").append(toIndentedString(author)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

