/**
 * 工作流接口文档
 * 工作流接口文档
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.chinacreator.c2.flow.rest.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Date;


/**
 * 部署信息
 */
@ApiModel(description = "部署信息")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-12-27T09:47:23.486+08:00")
public class WfDeploymentResponse   {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("deploymentTime")
  private Date deploymentTime = null;

  @JsonProperty("category")
  private String category = null;

  @JsonProperty("tenantId")
  private String tenantId = null;

  public WfDeploymentResponse id(String id) {
    this.id = id;
    return this;
  }

   /**
   * 部署id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "部署id")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public WfDeploymentResponse name(String name) {
    this.name = name;
    return this;
  }

   /**
   * 部署名称
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "部署名称")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public WfDeploymentResponse deploymentTime(Date deploymentTime) {
    this.deploymentTime = deploymentTime;
    return this;
  }

   /**
   * 部署时间
   * @return deploymentTime
  **/
  @ApiModelProperty(example = "null", value = "部署时间")
  public Date getDeploymentTime() {
    return deploymentTime;
  }

  public void setDeploymentTime(Date deploymentTime) {
    this.deploymentTime = deploymentTime;
  }

  public WfDeploymentResponse category(String category) {
    this.category = category;
    return this;
  }

   /**
   * 类别
   * @return category
  **/
  @ApiModelProperty(example = "null", value = "类别")
  public String getCategory() {
    return category;
  }

  public void setCategory(String category) {
    this.category = category;
  }

  public WfDeploymentResponse tenantId(String tenantId) {
    this.tenantId = tenantId;
    return this;
  }

   /**
   * 租户
   * @return tenantId
  **/
  @ApiModelProperty(example = "null", value = "租户")
  public String getTenantId() {
    return tenantId;
  }

  public void setTenantId(String tenantId) {
    this.tenantId = tenantId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WfDeploymentResponse wfDeploymentResponse = (WfDeploymentResponse) o;
    return Objects.equals(this.id, wfDeploymentResponse.id) &&
        Objects.equals(this.name, wfDeploymentResponse.name) &&
        Objects.equals(this.deploymentTime, wfDeploymentResponse.deploymentTime) &&
        Objects.equals(this.category, wfDeploymentResponse.category) &&
        Objects.equals(this.tenantId, wfDeploymentResponse.tenantId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, deploymentTime, category, tenantId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WfDeploymentResponse {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    deploymentTime: ").append(toIndentedString(deploymentTime)).append("\n");
    sb.append("    category: ").append(toIndentedString(category)).append("\n");
    sb.append("    tenantId: ").append(toIndentedString(tenantId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

