/**
 * 工作流接口文档
 * 工作流接口文档
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.chinacreator.c2.flow.rest.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.File;

import java.io.Serializable;
/**
 * 流程定义部署信息
 */
@ApiModel(description = "流程定义部署信息")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-12-28T16:50:41.068+08:00")
public class WfDeploymentRequest  implements Serializable {
  @JsonProperty("currentLoginUserId")
  private String currentLoginUserId = null;

  @JsonProperty("deployName")
  private String deployName = null;

  @JsonProperty("category")
  private String category = null;

  @JsonProperty("deployResource")
  private File deployResource = null;

  @JsonProperty("tenantId")
  private String tenantId = null;

  public WfDeploymentRequest currentLoginUserId(String currentLoginUserId) {
    this.currentLoginUserId = currentLoginUserId;
    return this;
  }

   /**
   * 模拟当前登陆用户，需要后台启用开关(当流程独立部署且未集成sso环境时调试使用)
   * @return currentLoginUserId
  **/
  @ApiModelProperty(example = "null", value = "模拟当前登陆用户，需要后台启用开关(当流程独立部署且未集成sso环境时调试使用)")
  public String getCurrentLoginUserId() {
    return currentLoginUserId;
  }

  public void setCurrentLoginUserId(String currentLoginUserId) {
    this.currentLoginUserId = currentLoginUserId;
  }

  public WfDeploymentRequest deployName(String deployName) {
    this.deployName = deployName;
    return this;
  }

   /**
   * 部署名称(要以bpmn20.xml或bpmn结尾)
   * @return deployName
  **/
  @ApiModelProperty(example = "null", required = true, value = "部署名称(要以bpmn20.xml或bpmn结尾)")
  public String getDeployName() {
    return deployName;
  }

  public void setDeployName(String deployName) {
    this.deployName = deployName;
  }

  public WfDeploymentRequest category(String category) {
    this.category = category;
    return this;
  }

   /**
   * 部署类别
   * @return category
  **/
  @ApiModelProperty(example = "null", value = "部署类别")
  public String getCategory() {
    return category;
  }

  public void setCategory(String category) {
    this.category = category;
  }

  public WfDeploymentRequest deployResource(File deployResource) {
    this.deployResource = deployResource;
    return this;
  }

   /**
   * 要部署的流程定义文件
   * @return deployResource
  **/
  @ApiModelProperty(example = "null", required = true, value = "要部署的流程定义文件")
  public File getDeployResource() {
    return deployResource;
  }

  public void setDeployResource(File deployResource) {
    this.deployResource = deployResource;
  }

  public WfDeploymentRequest tenantId(String tenantId) {
    this.tenantId = tenantId;
    return this;
  }

   /**
   * 租户(多应用共享流程中心时使用)
   * @return tenantId
  **/
  @ApiModelProperty(example = "null", value = "租户(多应用共享流程中心时使用)")
  public String getTenantId() {
    return tenantId;
  }

  public void setTenantId(String tenantId) {
    this.tenantId = tenantId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WfDeploymentRequest wfDeploymentRequest = (WfDeploymentRequest) o;
    return Objects.equals(this.currentLoginUserId, wfDeploymentRequest.currentLoginUserId) &&
        Objects.equals(this.deployName, wfDeploymentRequest.deployName) &&
        Objects.equals(this.category, wfDeploymentRequest.category) &&
        Objects.equals(this.deployResource, wfDeploymentRequest.deployResource) &&
        Objects.equals(this.tenantId, wfDeploymentRequest.tenantId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(currentLoginUserId, deployName, category, deployResource, tenantId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WfDeploymentRequest {\n");
    
    sb.append("    currentLoginUserId: ").append(toIndentedString(currentLoginUserId)).append("\n");
    sb.append("    deployName: ").append(toIndentedString(deployName)).append("\n");
    sb.append("    category: ").append(toIndentedString(category)).append("\n");
    sb.append("    deployResource: ").append(toIndentedString(deployResource)).append("\n");
    sb.append("    tenantId: ").append(toIndentedString(tenantId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

