/**
 * 工作流接口文档
 * 工作流接口文档
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.chinacreator.c2.flow.rest.model;

import java.util.Objects;
import com.chinacreator.c2.flow.rest.model.WfQueryVariable;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;


/**
 * 历史任务查询参数
 */
@ApiModel(description = "历史任务查询参数")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-12-15T15:13:20.386+08:00")
public class WfHistoricTaskInstanceQueryRequest   {
  @JsonProperty("start")
  private Integer start = null;

  @JsonProperty("size")
  private Integer size = null;

  @JsonProperty("sort")
  private String sort = null;

  @JsonProperty("order")
  private String order = null;

  @JsonProperty("taskId")
  private String taskId = null;

  @JsonProperty("processInstanceId")
  private String processInstanceId = null;

  @JsonProperty("processBusinessKey")
  private String processBusinessKey = null;

  @JsonProperty("processBusinessKeyLike")
  private String processBusinessKeyLike = null;

  @JsonProperty("processDefinitionId")
  private String processDefinitionId = null;

  @JsonProperty("processDefinitionKey")
  private String processDefinitionKey = null;

  @JsonProperty("processDefinitionKeyLike")
  private String processDefinitionKeyLike = null;

  @JsonProperty("processDefinitionName")
  private String processDefinitionName = null;

  @JsonProperty("processDefinitionNameLike")
  private String processDefinitionNameLike = null;

  @JsonProperty("executionId")
  private String executionId = null;

  @JsonProperty("taskName")
  private String taskName = null;

  @JsonProperty("taskNameLike")
  private String taskNameLike = null;

  @JsonProperty("taskDescription")
  private String taskDescription = null;

  @JsonProperty("taskDescriptionLike")
  private String taskDescriptionLike = null;

  @JsonProperty("taskDefinitionKey")
  private String taskDefinitionKey = null;

  @JsonProperty("taskDefinitionKeyLike")
  private String taskDefinitionKeyLike = null;

  @JsonProperty("taskDeleteReason")
  private String taskDeleteReason = null;

  @JsonProperty("taskDeleteReasonLike")
  private String taskDeleteReasonLike = null;

  @JsonProperty("taskAssignee")
  private String taskAssignee = null;

  @JsonProperty("taskAssigneeLike")
  private String taskAssigneeLike = null;

  @JsonProperty("taskOwner")
  private String taskOwner = null;

  @JsonProperty("taskOwnerLike")
  private String taskOwnerLike = null;

  @JsonProperty("taskInvolvedUser")
  private String taskInvolvedUser = null;

  @JsonProperty("taskPriority")
  private Integer taskPriority = null;

  @JsonProperty("taskMinPriority")
  private Integer taskMinPriority = null;

  @JsonProperty("taskMaxPriority")
  private Integer taskMaxPriority = null;

  @JsonProperty("finished")
  private Boolean finished = null;

  @JsonProperty("processFinished")
  private Boolean processFinished = null;

  @JsonProperty("parentTaskId")
  private String parentTaskId = null;

  @JsonProperty("dueDate")
  private Date dueDate = null;

  @JsonProperty("dueDateAfter")
  private Date dueDateAfter = null;

  @JsonProperty("dueDateBefore")
  private Date dueDateBefore = null;

  @JsonProperty("withoutDueDate")
  private Boolean withoutDueDate = null;

  @JsonProperty("taskCreatedOn")
  private Date taskCreatedOn = null;

  @JsonProperty("taskCreatedBefore")
  private Date taskCreatedBefore = null;

  @JsonProperty("taskCreatedAfter")
  private Date taskCreatedAfter = null;

  @JsonProperty("taskCompletedOn")
  private Date taskCompletedOn = null;

  @JsonProperty("taskCompletedBefore")
  private Date taskCompletedBefore = null;

  @JsonProperty("taskCompletedAfter")
  private Date taskCompletedAfter = null;

  @JsonProperty("includeTaskLocalVariables")
  private Boolean includeTaskLocalVariables = null;

  @JsonProperty("includeProcessVariables")
  private Boolean includeProcessVariables = null;

  @JsonProperty("taskVariables")
  private List<WfQueryVariable> taskVariables = new ArrayList<WfQueryVariable>();

  @JsonProperty("processVariables")
  private List<WfQueryVariable> processVariables = new ArrayList<WfQueryVariable>();

  @JsonProperty("tenantId")
  private String tenantId = null;

  @JsonProperty("tenantIdLike")
  private String tenantIdLike = null;

  @JsonProperty("withoutTenantId")
  private Boolean withoutTenantId = null;

  public WfHistoricTaskInstanceQueryRequest start(Integer start) {
    this.start = start;
    return this;
  }

   /**
   * 开始行
   * @return start
  **/
  @ApiModelProperty(example = "null", value = "开始行")
  public Integer getStart() {
    return start;
  }

  public void setStart(Integer start) {
    this.start = start;
  }

  public WfHistoricTaskInstanceQueryRequest size(Integer size) {
    this.size = size;
    return this;
  }

   /**
   * 请求大小
   * @return size
  **/
  @ApiModelProperty(example = "null", value = "请求大小")
  public Integer getSize() {
    return size;
  }

  public void setSize(Integer size) {
    this.size = size;
  }

  public WfHistoricTaskInstanceQueryRequest sort(String sort) {
    this.sort = sort;
    return this;
  }

   /**
   * 排序字段
   * @return sort
  **/
  @ApiModelProperty(example = "null", value = "排序字段")
  public String getSort() {
    return sort;
  }

  public void setSort(String sort) {
    this.sort = sort;
  }

  public WfHistoricTaskInstanceQueryRequest order(String order) {
    this.order = order;
    return this;
  }

   /**
   * 排序方式asc/desc
   * @return order
  **/
  @ApiModelProperty(example = "null", value = "排序方式asc/desc")
  public String getOrder() {
    return order;
  }

  public void setOrder(String order) {
    this.order = order;
  }

  public WfHistoricTaskInstanceQueryRequest taskId(String taskId) {
    this.taskId = taskId;
    return this;
  }

   /**
   * 任务id
   * @return taskId
  **/
  @ApiModelProperty(example = "null", value = "任务id")
  public String getTaskId() {
    return taskId;
  }

  public void setTaskId(String taskId) {
    this.taskId = taskId;
  }

  public WfHistoricTaskInstanceQueryRequest processInstanceId(String processInstanceId) {
    this.processInstanceId = processInstanceId;
    return this;
  }

   /**
   * 流程实例id
   * @return processInstanceId
  **/
  @ApiModelProperty(example = "null", value = "流程实例id")
  public String getProcessInstanceId() {
    return processInstanceId;
  }

  public void setProcessInstanceId(String processInstanceId) {
    this.processInstanceId = processInstanceId;
  }

  public WfHistoricTaskInstanceQueryRequest processBusinessKey(String processBusinessKey) {
    this.processBusinessKey = processBusinessKey;
    return this;
  }

   /**
   * 业务主键
   * @return processBusinessKey
  **/
  @ApiModelProperty(example = "null", value = "业务主键")
  public String getProcessBusinessKey() {
    return processBusinessKey;
  }

  public void setProcessBusinessKey(String processBusinessKey) {
    this.processBusinessKey = processBusinessKey;
  }

  public WfHistoricTaskInstanceQueryRequest processBusinessKeyLike(String processBusinessKeyLike) {
    this.processBusinessKeyLike = processBusinessKeyLike;
    return this;
  }

   /**
   * 业务主键模糊
   * @return processBusinessKeyLike
  **/
  @ApiModelProperty(example = "null", value = "业务主键模糊")
  public String getProcessBusinessKeyLike() {
    return processBusinessKeyLike;
  }

  public void setProcessBusinessKeyLike(String processBusinessKeyLike) {
    this.processBusinessKeyLike = processBusinessKeyLike;
  }

  public WfHistoricTaskInstanceQueryRequest processDefinitionId(String processDefinitionId) {
    this.processDefinitionId = processDefinitionId;
    return this;
  }

   /**
   * 流程定义id
   * @return processDefinitionId
  **/
  @ApiModelProperty(example = "null", value = "流程定义id")
  public String getProcessDefinitionId() {
    return processDefinitionId;
  }

  public void setProcessDefinitionId(String processDefinitionId) {
    this.processDefinitionId = processDefinitionId;
  }

  public WfHistoricTaskInstanceQueryRequest processDefinitionKey(String processDefinitionKey) {
    this.processDefinitionKey = processDefinitionKey;
    return this;
  }

   /**
   * 流程定义key
   * @return processDefinitionKey
  **/
  @ApiModelProperty(example = "null", value = "流程定义key")
  public String getProcessDefinitionKey() {
    return processDefinitionKey;
  }

  public void setProcessDefinitionKey(String processDefinitionKey) {
    this.processDefinitionKey = processDefinitionKey;
  }

  public WfHistoricTaskInstanceQueryRequest processDefinitionKeyLike(String processDefinitionKeyLike) {
    this.processDefinitionKeyLike = processDefinitionKeyLike;
    return this;
  }

   /**
   * 流程定义key模糊
   * @return processDefinitionKeyLike
  **/
  @ApiModelProperty(example = "null", value = "流程定义key模糊")
  public String getProcessDefinitionKeyLike() {
    return processDefinitionKeyLike;
  }

  public void setProcessDefinitionKeyLike(String processDefinitionKeyLike) {
    this.processDefinitionKeyLike = processDefinitionKeyLike;
  }

  public WfHistoricTaskInstanceQueryRequest processDefinitionName(String processDefinitionName) {
    this.processDefinitionName = processDefinitionName;
    return this;
  }

   /**
   * 流程定义名称
   * @return processDefinitionName
  **/
  @ApiModelProperty(example = "null", value = "流程定义名称")
  public String getProcessDefinitionName() {
    return processDefinitionName;
  }

  public void setProcessDefinitionName(String processDefinitionName) {
    this.processDefinitionName = processDefinitionName;
  }

  public WfHistoricTaskInstanceQueryRequest processDefinitionNameLike(String processDefinitionNameLike) {
    this.processDefinitionNameLike = processDefinitionNameLike;
    return this;
  }

   /**
   * 流程定义名称模糊
   * @return processDefinitionNameLike
  **/
  @ApiModelProperty(example = "null", value = "流程定义名称模糊")
  public String getProcessDefinitionNameLike() {
    return processDefinitionNameLike;
  }

  public void setProcessDefinitionNameLike(String processDefinitionNameLike) {
    this.processDefinitionNameLike = processDefinitionNameLike;
  }

  public WfHistoricTaskInstanceQueryRequest executionId(String executionId) {
    this.executionId = executionId;
    return this;
  }

   /**
   * 任务执行id
   * @return executionId
  **/
  @ApiModelProperty(example = "null", value = "任务执行id")
  public String getExecutionId() {
    return executionId;
  }

  public void setExecutionId(String executionId) {
    this.executionId = executionId;
  }

  public WfHistoricTaskInstanceQueryRequest taskName(String taskName) {
    this.taskName = taskName;
    return this;
  }

   /**
   * 任务名称
   * @return taskName
  **/
  @ApiModelProperty(example = "null", value = "任务名称")
  public String getTaskName() {
    return taskName;
  }

  public void setTaskName(String taskName) {
    this.taskName = taskName;
  }

  public WfHistoricTaskInstanceQueryRequest taskNameLike(String taskNameLike) {
    this.taskNameLike = taskNameLike;
    return this;
  }

   /**
   * 任务名称模糊
   * @return taskNameLike
  **/
  @ApiModelProperty(example = "null", value = "任务名称模糊")
  public String getTaskNameLike() {
    return taskNameLike;
  }

  public void setTaskNameLike(String taskNameLike) {
    this.taskNameLike = taskNameLike;
  }

  public WfHistoricTaskInstanceQueryRequest taskDescription(String taskDescription) {
    this.taskDescription = taskDescription;
    return this;
  }

   /**
   * 任务描述
   * @return taskDescription
  **/
  @ApiModelProperty(example = "null", value = "任务描述")
  public String getTaskDescription() {
    return taskDescription;
  }

  public void setTaskDescription(String taskDescription) {
    this.taskDescription = taskDescription;
  }

  public WfHistoricTaskInstanceQueryRequest taskDescriptionLike(String taskDescriptionLike) {
    this.taskDescriptionLike = taskDescriptionLike;
    return this;
  }

   /**
   * 任务描述模糊
   * @return taskDescriptionLike
  **/
  @ApiModelProperty(example = "null", value = "任务描述模糊")
  public String getTaskDescriptionLike() {
    return taskDescriptionLike;
  }

  public void setTaskDescriptionLike(String taskDescriptionLike) {
    this.taskDescriptionLike = taskDescriptionLike;
  }

  public WfHistoricTaskInstanceQueryRequest taskDefinitionKey(String taskDefinitionKey) {
    this.taskDefinitionKey = taskDefinitionKey;
    return this;
  }

   /**
   * 任务环节key
   * @return taskDefinitionKey
  **/
  @ApiModelProperty(example = "null", value = "任务环节key")
  public String getTaskDefinitionKey() {
    return taskDefinitionKey;
  }

  public void setTaskDefinitionKey(String taskDefinitionKey) {
    this.taskDefinitionKey = taskDefinitionKey;
  }

  public WfHistoricTaskInstanceQueryRequest taskDefinitionKeyLike(String taskDefinitionKeyLike) {
    this.taskDefinitionKeyLike = taskDefinitionKeyLike;
    return this;
  }

   /**
   * 任务环节key模糊
   * @return taskDefinitionKeyLike
  **/
  @ApiModelProperty(example = "null", value = "任务环节key模糊")
  public String getTaskDefinitionKeyLike() {
    return taskDefinitionKeyLike;
  }

  public void setTaskDefinitionKeyLike(String taskDefinitionKeyLike) {
    this.taskDefinitionKeyLike = taskDefinitionKeyLike;
  }

  public WfHistoricTaskInstanceQueryRequest taskDeleteReason(String taskDeleteReason) {
    this.taskDeleteReason = taskDeleteReason;
    return this;
  }

   /**
   * 任务删除原因
   * @return taskDeleteReason
  **/
  @ApiModelProperty(example = "null", value = "任务删除原因")
  public String getTaskDeleteReason() {
    return taskDeleteReason;
  }

  public void setTaskDeleteReason(String taskDeleteReason) {
    this.taskDeleteReason = taskDeleteReason;
  }

  public WfHistoricTaskInstanceQueryRequest taskDeleteReasonLike(String taskDeleteReasonLike) {
    this.taskDeleteReasonLike = taskDeleteReasonLike;
    return this;
  }

   /**
   * 任务删除原因模糊
   * @return taskDeleteReasonLike
  **/
  @ApiModelProperty(example = "null", value = "任务删除原因模糊")
  public String getTaskDeleteReasonLike() {
    return taskDeleteReasonLike;
  }

  public void setTaskDeleteReasonLike(String taskDeleteReasonLike) {
    this.taskDeleteReasonLike = taskDeleteReasonLike;
  }

  public WfHistoricTaskInstanceQueryRequest taskAssignee(String taskAssignee) {
    this.taskAssignee = taskAssignee;
    return this;
  }

   /**
   * 任务处理人
   * @return taskAssignee
  **/
  @ApiModelProperty(example = "null", value = "任务处理人")
  public String getTaskAssignee() {
    return taskAssignee;
  }

  public void setTaskAssignee(String taskAssignee) {
    this.taskAssignee = taskAssignee;
  }

  public WfHistoricTaskInstanceQueryRequest taskAssigneeLike(String taskAssigneeLike) {
    this.taskAssigneeLike = taskAssigneeLike;
    return this;
  }

   /**
   * 任务处理人模糊
   * @return taskAssigneeLike
  **/
  @ApiModelProperty(example = "null", value = "任务处理人模糊")
  public String getTaskAssigneeLike() {
    return taskAssigneeLike;
  }

  public void setTaskAssigneeLike(String taskAssigneeLike) {
    this.taskAssigneeLike = taskAssigneeLike;
  }

  public WfHistoricTaskInstanceQueryRequest taskOwner(String taskOwner) {
    this.taskOwner = taskOwner;
    return this;
  }

   /**
   * 任务所有者
   * @return taskOwner
  **/
  @ApiModelProperty(example = "null", value = "任务所有者")
  public String getTaskOwner() {
    return taskOwner;
  }

  public void setTaskOwner(String taskOwner) {
    this.taskOwner = taskOwner;
  }

  public WfHistoricTaskInstanceQueryRequest taskOwnerLike(String taskOwnerLike) {
    this.taskOwnerLike = taskOwnerLike;
    return this;
  }

   /**
   * 任务所有者模糊
   * @return taskOwnerLike
  **/
  @ApiModelProperty(example = "null", value = "任务所有者模糊")
  public String getTaskOwnerLike() {
    return taskOwnerLike;
  }

  public void setTaskOwnerLike(String taskOwnerLike) {
    this.taskOwnerLike = taskOwnerLike;
  }

  public WfHistoricTaskInstanceQueryRequest taskInvolvedUser(String taskInvolvedUser) {
    this.taskInvolvedUser = taskInvolvedUser;
    return this;
  }

   /**
   * 任务参与者(处理人、候选人、所有者)
   * @return taskInvolvedUser
  **/
  @ApiModelProperty(example = "null", value = "任务参与者(处理人、候选人、所有者)")
  public String getTaskInvolvedUser() {
    return taskInvolvedUser;
  }

  public void setTaskInvolvedUser(String taskInvolvedUser) {
    this.taskInvolvedUser = taskInvolvedUser;
  }

  public WfHistoricTaskInstanceQueryRequest taskPriority(Integer taskPriority) {
    this.taskPriority = taskPriority;
    return this;
  }

   /**
   * 任务优先级
   * @return taskPriority
  **/
  @ApiModelProperty(example = "null", value = "任务优先级")
  public Integer getTaskPriority() {
    return taskPriority;
  }

  public void setTaskPriority(Integer taskPriority) {
    this.taskPriority = taskPriority;
  }

  public WfHistoricTaskInstanceQueryRequest taskMinPriority(Integer taskMinPriority) {
    this.taskMinPriority = taskMinPriority;
    return this;
  }

   /**
   * 任务优先级下区间
   * @return taskMinPriority
  **/
  @ApiModelProperty(example = "null", value = "任务优先级下区间")
  public Integer getTaskMinPriority() {
    return taskMinPriority;
  }

  public void setTaskMinPriority(Integer taskMinPriority) {
    this.taskMinPriority = taskMinPriority;
  }

  public WfHistoricTaskInstanceQueryRequest taskMaxPriority(Integer taskMaxPriority) {
    this.taskMaxPriority = taskMaxPriority;
    return this;
  }

   /**
   * 任务优先级上区间
   * @return taskMaxPriority
  **/
  @ApiModelProperty(example = "null", value = "任务优先级上区间")
  public Integer getTaskMaxPriority() {
    return taskMaxPriority;
  }

  public void setTaskMaxPriority(Integer taskMaxPriority) {
    this.taskMaxPriority = taskMaxPriority;
  }

  public WfHistoricTaskInstanceQueryRequest finished(Boolean finished) {
    this.finished = finished;
    return this;
  }

   /**
   * 任务是否完成
   * @return finished
  **/
  @ApiModelProperty(example = "null", value = "任务是否完成")
  public Boolean getFinished() {
    return finished;
  }

  public void setFinished(Boolean finished) {
    this.finished = finished;
  }

  public WfHistoricTaskInstanceQueryRequest processFinished(Boolean processFinished) {
    this.processFinished = processFinished;
    return this;
  }

   /**
   * 流程是否完成
   * @return processFinished
  **/
  @ApiModelProperty(example = "null", value = "流程是否完成")
  public Boolean getProcessFinished() {
    return processFinished;
  }

  public void setProcessFinished(Boolean processFinished) {
    this.processFinished = processFinished;
  }

  public WfHistoricTaskInstanceQueryRequest parentTaskId(String parentTaskId) {
    this.parentTaskId = parentTaskId;
    return this;
  }

   /**
   * 父任务id
   * @return parentTaskId
  **/
  @ApiModelProperty(example = "null", value = "父任务id")
  public String getParentTaskId() {
    return parentTaskId;
  }

  public void setParentTaskId(String parentTaskId) {
    this.parentTaskId = parentTaskId;
  }

  public WfHistoricTaskInstanceQueryRequest dueDate(Date dueDate) {
    this.dueDate = dueDate;
    return this;
  }

   /**
   * 任务过期时间
   * @return dueDate
  **/
  @ApiModelProperty(example = "null", value = "任务过期时间")
  public Date getDueDate() {
    return dueDate;
  }

  public void setDueDate(Date dueDate) {
    this.dueDate = dueDate;
  }

  public WfHistoricTaskInstanceQueryRequest dueDateAfter(Date dueDateAfter) {
    this.dueDateAfter = dueDateAfter;
    return this;
  }

   /**
   * 任务过期时间晚于
   * @return dueDateAfter
  **/
  @ApiModelProperty(example = "null", value = "任务过期时间晚于")
  public Date getDueDateAfter() {
    return dueDateAfter;
  }

  public void setDueDateAfter(Date dueDateAfter) {
    this.dueDateAfter = dueDateAfter;
  }

  public WfHistoricTaskInstanceQueryRequest dueDateBefore(Date dueDateBefore) {
    this.dueDateBefore = dueDateBefore;
    return this;
  }

   /**
   * 任务过期时间早于
   * @return dueDateBefore
  **/
  @ApiModelProperty(example = "null", value = "任务过期时间早于")
  public Date getDueDateBefore() {
    return dueDateBefore;
  }

  public void setDueDateBefore(Date dueDateBefore) {
    this.dueDateBefore = dueDateBefore;
  }

  public WfHistoricTaskInstanceQueryRequest withoutDueDate(Boolean withoutDueDate) {
    this.withoutDueDate = withoutDueDate;
    return this;
  }

   /**
   * 放弃过期时间过滤
   * @return withoutDueDate
  **/
  @ApiModelProperty(example = "null", value = "放弃过期时间过滤")
  public Boolean getWithoutDueDate() {
    return withoutDueDate;
  }

  public void setWithoutDueDate(Boolean withoutDueDate) {
    this.withoutDueDate = withoutDueDate;
  }

  public WfHistoricTaskInstanceQueryRequest taskCreatedOn(Date taskCreatedOn) {
    this.taskCreatedOn = taskCreatedOn;
    return this;
  }

   /**
   * 任务创建时间
   * @return taskCreatedOn
  **/
  @ApiModelProperty(example = "null", value = "任务创建时间")
  public Date getTaskCreatedOn() {
    return taskCreatedOn;
  }

  public void setTaskCreatedOn(Date taskCreatedOn) {
    this.taskCreatedOn = taskCreatedOn;
  }

  public WfHistoricTaskInstanceQueryRequest taskCreatedBefore(Date taskCreatedBefore) {
    this.taskCreatedBefore = taskCreatedBefore;
    return this;
  }

   /**
   * 任务创建时间早于
   * @return taskCreatedBefore
  **/
  @ApiModelProperty(example = "null", value = "任务创建时间早于")
  public Date getTaskCreatedBefore() {
    return taskCreatedBefore;
  }

  public void setTaskCreatedBefore(Date taskCreatedBefore) {
    this.taskCreatedBefore = taskCreatedBefore;
  }

  public WfHistoricTaskInstanceQueryRequest taskCreatedAfter(Date taskCreatedAfter) {
    this.taskCreatedAfter = taskCreatedAfter;
    return this;
  }

   /**
   * 任务创建时间晚于
   * @return taskCreatedAfter
  **/
  @ApiModelProperty(example = "null", value = "任务创建时间晚于")
  public Date getTaskCreatedAfter() {
    return taskCreatedAfter;
  }

  public void setTaskCreatedAfter(Date taskCreatedAfter) {
    this.taskCreatedAfter = taskCreatedAfter;
  }

  public WfHistoricTaskInstanceQueryRequest taskCompletedOn(Date taskCompletedOn) {
    this.taskCompletedOn = taskCompletedOn;
    return this;
  }

   /**
   * 任务完成时间
   * @return taskCompletedOn
  **/
  @ApiModelProperty(example = "null", value = "任务完成时间")
  public Date getTaskCompletedOn() {
    return taskCompletedOn;
  }

  public void setTaskCompletedOn(Date taskCompletedOn) {
    this.taskCompletedOn = taskCompletedOn;
  }

  public WfHistoricTaskInstanceQueryRequest taskCompletedBefore(Date taskCompletedBefore) {
    this.taskCompletedBefore = taskCompletedBefore;
    return this;
  }

   /**
   * 任务完成时间早于
   * @return taskCompletedBefore
  **/
  @ApiModelProperty(example = "null", value = "任务完成时间早于")
  public Date getTaskCompletedBefore() {
    return taskCompletedBefore;
  }

  public void setTaskCompletedBefore(Date taskCompletedBefore) {
    this.taskCompletedBefore = taskCompletedBefore;
  }

  public WfHistoricTaskInstanceQueryRequest taskCompletedAfter(Date taskCompletedAfter) {
    this.taskCompletedAfter = taskCompletedAfter;
    return this;
  }

   /**
   * 任务完成时间晚于
   * @return taskCompletedAfter
  **/
  @ApiModelProperty(example = "null", value = "任务完成时间晚于")
  public Date getTaskCompletedAfter() {
    return taskCompletedAfter;
  }

  public void setTaskCompletedAfter(Date taskCompletedAfter) {
    this.taskCompletedAfter = taskCompletedAfter;
  }

  public WfHistoricTaskInstanceQueryRequest includeTaskLocalVariables(Boolean includeTaskLocalVariables) {
    this.includeTaskLocalVariables = includeTaskLocalVariables;
    return this;
  }

   /**
   * 是否只查询包含流程环节变量任务
   * @return includeTaskLocalVariables
  **/
  @ApiModelProperty(example = "null", value = "是否只查询包含流程环节变量任务")
  public Boolean getIncludeTaskLocalVariables() {
    return includeTaskLocalVariables;
  }

  public void setIncludeTaskLocalVariables(Boolean includeTaskLocalVariables) {
    this.includeTaskLocalVariables = includeTaskLocalVariables;
  }

  public WfHistoricTaskInstanceQueryRequest includeProcessVariables(Boolean includeProcessVariables) {
    this.includeProcessVariables = includeProcessVariables;
    return this;
  }

   /**
   * 是否只查询包含流程环节变量和全局变量任务
   * @return includeProcessVariables
  **/
  @ApiModelProperty(example = "null", value = "是否只查询包含流程环节变量和全局变量任务")
  public Boolean getIncludeProcessVariables() {
    return includeProcessVariables;
  }

  public void setIncludeProcessVariables(Boolean includeProcessVariables) {
    this.includeProcessVariables = includeProcessVariables;
  }

  public WfHistoricTaskInstanceQueryRequest taskVariables(List<WfQueryVariable> taskVariables) {
    this.taskVariables = taskVariables;
    return this;
  }

  public WfHistoricTaskInstanceQueryRequest addTaskVariablesItem(WfQueryVariable taskVariablesItem) {
    this.taskVariables.add(taskVariablesItem);
    return this;
  }

   /**
   * 任务变量条件(LOCAL)
   * @return taskVariables
  **/
  @ApiModelProperty(example = "null", value = "任务变量条件(LOCAL)")
  public List<WfQueryVariable> getTaskVariables() {
    return taskVariables;
  }

  public void setTaskVariables(List<WfQueryVariable> taskVariables) {
    this.taskVariables = taskVariables;
  }

  public WfHistoricTaskInstanceQueryRequest processVariables(List<WfQueryVariable> processVariables) {
    this.processVariables = processVariables;
    return this;
  }

  public WfHistoricTaskInstanceQueryRequest addProcessVariablesItem(WfQueryVariable processVariablesItem) {
    this.processVariables.add(processVariablesItem);
    return this;
  }

   /**
   * 任务所在流程变量条件(GLOBAL)
   * @return processVariables
  **/
  @ApiModelProperty(example = "null", value = "任务所在流程变量条件(GLOBAL)")
  public List<WfQueryVariable> getProcessVariables() {
    return processVariables;
  }

  public void setProcessVariables(List<WfQueryVariable> processVariables) {
    this.processVariables = processVariables;
  }

  public WfHistoricTaskInstanceQueryRequest tenantId(String tenantId) {
    this.tenantId = tenantId;
    return this;
  }

   /**
   * 租户
   * @return tenantId
  **/
  @ApiModelProperty(example = "null", value = "租户")
  public String getTenantId() {
    return tenantId;
  }

  public void setTenantId(String tenantId) {
    this.tenantId = tenantId;
  }

  public WfHistoricTaskInstanceQueryRequest tenantIdLike(String tenantIdLike) {
    this.tenantIdLike = tenantIdLike;
    return this;
  }

   /**
   * 租户模糊
   * @return tenantIdLike
  **/
  @ApiModelProperty(example = "null", value = "租户模糊")
  public String getTenantIdLike() {
    return tenantIdLike;
  }

  public void setTenantIdLike(String tenantIdLike) {
    this.tenantIdLike = tenantIdLike;
  }

  public WfHistoricTaskInstanceQueryRequest withoutTenantId(Boolean withoutTenantId) {
    this.withoutTenantId = withoutTenantId;
    return this;
  }

   /**
   * 忽略租户条件
   * @return withoutTenantId
  **/
  @ApiModelProperty(example = "null", value = "忽略租户条件")
  public Boolean getWithoutTenantId() {
    return withoutTenantId;
  }

  public void setWithoutTenantId(Boolean withoutTenantId) {
    this.withoutTenantId = withoutTenantId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WfHistoricTaskInstanceQueryRequest wfHistoricTaskInstanceQueryRequest = (WfHistoricTaskInstanceQueryRequest) o;
    return Objects.equals(this.start, wfHistoricTaskInstanceQueryRequest.start) &&
        Objects.equals(this.size, wfHistoricTaskInstanceQueryRequest.size) &&
        Objects.equals(this.sort, wfHistoricTaskInstanceQueryRequest.sort) &&
        Objects.equals(this.order, wfHistoricTaskInstanceQueryRequest.order) &&
        Objects.equals(this.taskId, wfHistoricTaskInstanceQueryRequest.taskId) &&
        Objects.equals(this.processInstanceId, wfHistoricTaskInstanceQueryRequest.processInstanceId) &&
        Objects.equals(this.processBusinessKey, wfHistoricTaskInstanceQueryRequest.processBusinessKey) &&
        Objects.equals(this.processBusinessKeyLike, wfHistoricTaskInstanceQueryRequest.processBusinessKeyLike) &&
        Objects.equals(this.processDefinitionId, wfHistoricTaskInstanceQueryRequest.processDefinitionId) &&
        Objects.equals(this.processDefinitionKey, wfHistoricTaskInstanceQueryRequest.processDefinitionKey) &&
        Objects.equals(this.processDefinitionKeyLike, wfHistoricTaskInstanceQueryRequest.processDefinitionKeyLike) &&
        Objects.equals(this.processDefinitionName, wfHistoricTaskInstanceQueryRequest.processDefinitionName) &&
        Objects.equals(this.processDefinitionNameLike, wfHistoricTaskInstanceQueryRequest.processDefinitionNameLike) &&
        Objects.equals(this.executionId, wfHistoricTaskInstanceQueryRequest.executionId) &&
        Objects.equals(this.taskName, wfHistoricTaskInstanceQueryRequest.taskName) &&
        Objects.equals(this.taskNameLike, wfHistoricTaskInstanceQueryRequest.taskNameLike) &&
        Objects.equals(this.taskDescription, wfHistoricTaskInstanceQueryRequest.taskDescription) &&
        Objects.equals(this.taskDescriptionLike, wfHistoricTaskInstanceQueryRequest.taskDescriptionLike) &&
        Objects.equals(this.taskDefinitionKey, wfHistoricTaskInstanceQueryRequest.taskDefinitionKey) &&
        Objects.equals(this.taskDefinitionKeyLike, wfHistoricTaskInstanceQueryRequest.taskDefinitionKeyLike) &&
        Objects.equals(this.taskDeleteReason, wfHistoricTaskInstanceQueryRequest.taskDeleteReason) &&
        Objects.equals(this.taskDeleteReasonLike, wfHistoricTaskInstanceQueryRequest.taskDeleteReasonLike) &&
        Objects.equals(this.taskAssignee, wfHistoricTaskInstanceQueryRequest.taskAssignee) &&
        Objects.equals(this.taskAssigneeLike, wfHistoricTaskInstanceQueryRequest.taskAssigneeLike) &&
        Objects.equals(this.taskOwner, wfHistoricTaskInstanceQueryRequest.taskOwner) &&
        Objects.equals(this.taskOwnerLike, wfHistoricTaskInstanceQueryRequest.taskOwnerLike) &&
        Objects.equals(this.taskInvolvedUser, wfHistoricTaskInstanceQueryRequest.taskInvolvedUser) &&
        Objects.equals(this.taskPriority, wfHistoricTaskInstanceQueryRequest.taskPriority) &&
        Objects.equals(this.taskMinPriority, wfHistoricTaskInstanceQueryRequest.taskMinPriority) &&
        Objects.equals(this.taskMaxPriority, wfHistoricTaskInstanceQueryRequest.taskMaxPriority) &&
        Objects.equals(this.finished, wfHistoricTaskInstanceQueryRequest.finished) &&
        Objects.equals(this.processFinished, wfHistoricTaskInstanceQueryRequest.processFinished) &&
        Objects.equals(this.parentTaskId, wfHistoricTaskInstanceQueryRequest.parentTaskId) &&
        Objects.equals(this.dueDate, wfHistoricTaskInstanceQueryRequest.dueDate) &&
        Objects.equals(this.dueDateAfter, wfHistoricTaskInstanceQueryRequest.dueDateAfter) &&
        Objects.equals(this.dueDateBefore, wfHistoricTaskInstanceQueryRequest.dueDateBefore) &&
        Objects.equals(this.withoutDueDate, wfHistoricTaskInstanceQueryRequest.withoutDueDate) &&
        Objects.equals(this.taskCreatedOn, wfHistoricTaskInstanceQueryRequest.taskCreatedOn) &&
        Objects.equals(this.taskCreatedBefore, wfHistoricTaskInstanceQueryRequest.taskCreatedBefore) &&
        Objects.equals(this.taskCreatedAfter, wfHistoricTaskInstanceQueryRequest.taskCreatedAfter) &&
        Objects.equals(this.taskCompletedOn, wfHistoricTaskInstanceQueryRequest.taskCompletedOn) &&
        Objects.equals(this.taskCompletedBefore, wfHistoricTaskInstanceQueryRequest.taskCompletedBefore) &&
        Objects.equals(this.taskCompletedAfter, wfHistoricTaskInstanceQueryRequest.taskCompletedAfter) &&
        Objects.equals(this.includeTaskLocalVariables, wfHistoricTaskInstanceQueryRequest.includeTaskLocalVariables) &&
        Objects.equals(this.includeProcessVariables, wfHistoricTaskInstanceQueryRequest.includeProcessVariables) &&
        Objects.equals(this.taskVariables, wfHistoricTaskInstanceQueryRequest.taskVariables) &&
        Objects.equals(this.processVariables, wfHistoricTaskInstanceQueryRequest.processVariables) &&
        Objects.equals(this.tenantId, wfHistoricTaskInstanceQueryRequest.tenantId) &&
        Objects.equals(this.tenantIdLike, wfHistoricTaskInstanceQueryRequest.tenantIdLike) &&
        Objects.equals(this.withoutTenantId, wfHistoricTaskInstanceQueryRequest.withoutTenantId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(start, size, sort, order, taskId, processInstanceId, processBusinessKey, processBusinessKeyLike, processDefinitionId, processDefinitionKey, processDefinitionKeyLike, processDefinitionName, processDefinitionNameLike, executionId, taskName, taskNameLike, taskDescription, taskDescriptionLike, taskDefinitionKey, taskDefinitionKeyLike, taskDeleteReason, taskDeleteReasonLike, taskAssignee, taskAssigneeLike, taskOwner, taskOwnerLike, taskInvolvedUser, taskPriority, taskMinPriority, taskMaxPriority, finished, processFinished, parentTaskId, dueDate, dueDateAfter, dueDateBefore, withoutDueDate, taskCreatedOn, taskCreatedBefore, taskCreatedAfter, taskCompletedOn, taskCompletedBefore, taskCompletedAfter, includeTaskLocalVariables, includeProcessVariables, taskVariables, processVariables, tenantId, tenantIdLike, withoutTenantId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WfHistoricTaskInstanceQueryRequest {\n");
    
    sb.append("    start: ").append(toIndentedString(start)).append("\n");
    sb.append("    size: ").append(toIndentedString(size)).append("\n");
    sb.append("    sort: ").append(toIndentedString(sort)).append("\n");
    sb.append("    order: ").append(toIndentedString(order)).append("\n");
    sb.append("    taskId: ").append(toIndentedString(taskId)).append("\n");
    sb.append("    processInstanceId: ").append(toIndentedString(processInstanceId)).append("\n");
    sb.append("    processBusinessKey: ").append(toIndentedString(processBusinessKey)).append("\n");
    sb.append("    processBusinessKeyLike: ").append(toIndentedString(processBusinessKeyLike)).append("\n");
    sb.append("    processDefinitionId: ").append(toIndentedString(processDefinitionId)).append("\n");
    sb.append("    processDefinitionKey: ").append(toIndentedString(processDefinitionKey)).append("\n");
    sb.append("    processDefinitionKeyLike: ").append(toIndentedString(processDefinitionKeyLike)).append("\n");
    sb.append("    processDefinitionName: ").append(toIndentedString(processDefinitionName)).append("\n");
    sb.append("    processDefinitionNameLike: ").append(toIndentedString(processDefinitionNameLike)).append("\n");
    sb.append("    executionId: ").append(toIndentedString(executionId)).append("\n");
    sb.append("    taskName: ").append(toIndentedString(taskName)).append("\n");
    sb.append("    taskNameLike: ").append(toIndentedString(taskNameLike)).append("\n");
    sb.append("    taskDescription: ").append(toIndentedString(taskDescription)).append("\n");
    sb.append("    taskDescriptionLike: ").append(toIndentedString(taskDescriptionLike)).append("\n");
    sb.append("    taskDefinitionKey: ").append(toIndentedString(taskDefinitionKey)).append("\n");
    sb.append("    taskDefinitionKeyLike: ").append(toIndentedString(taskDefinitionKeyLike)).append("\n");
    sb.append("    taskDeleteReason: ").append(toIndentedString(taskDeleteReason)).append("\n");
    sb.append("    taskDeleteReasonLike: ").append(toIndentedString(taskDeleteReasonLike)).append("\n");
    sb.append("    taskAssignee: ").append(toIndentedString(taskAssignee)).append("\n");
    sb.append("    taskAssigneeLike: ").append(toIndentedString(taskAssigneeLike)).append("\n");
    sb.append("    taskOwner: ").append(toIndentedString(taskOwner)).append("\n");
    sb.append("    taskOwnerLike: ").append(toIndentedString(taskOwnerLike)).append("\n");
    sb.append("    taskInvolvedUser: ").append(toIndentedString(taskInvolvedUser)).append("\n");
    sb.append("    taskPriority: ").append(toIndentedString(taskPriority)).append("\n");
    sb.append("    taskMinPriority: ").append(toIndentedString(taskMinPriority)).append("\n");
    sb.append("    taskMaxPriority: ").append(toIndentedString(taskMaxPriority)).append("\n");
    sb.append("    finished: ").append(toIndentedString(finished)).append("\n");
    sb.append("    processFinished: ").append(toIndentedString(processFinished)).append("\n");
    sb.append("    parentTaskId: ").append(toIndentedString(parentTaskId)).append("\n");
    sb.append("    dueDate: ").append(toIndentedString(dueDate)).append("\n");
    sb.append("    dueDateAfter: ").append(toIndentedString(dueDateAfter)).append("\n");
    sb.append("    dueDateBefore: ").append(toIndentedString(dueDateBefore)).append("\n");
    sb.append("    withoutDueDate: ").append(toIndentedString(withoutDueDate)).append("\n");
    sb.append("    taskCreatedOn: ").append(toIndentedString(taskCreatedOn)).append("\n");
    sb.append("    taskCreatedBefore: ").append(toIndentedString(taskCreatedBefore)).append("\n");
    sb.append("    taskCreatedAfter: ").append(toIndentedString(taskCreatedAfter)).append("\n");
    sb.append("    taskCompletedOn: ").append(toIndentedString(taskCompletedOn)).append("\n");
    sb.append("    taskCompletedBefore: ").append(toIndentedString(taskCompletedBefore)).append("\n");
    sb.append("    taskCompletedAfter: ").append(toIndentedString(taskCompletedAfter)).append("\n");
    sb.append("    includeTaskLocalVariables: ").append(toIndentedString(includeTaskLocalVariables)).append("\n");
    sb.append("    includeProcessVariables: ").append(toIndentedString(includeProcessVariables)).append("\n");
    sb.append("    taskVariables: ").append(toIndentedString(taskVariables)).append("\n");
    sb.append("    processVariables: ").append(toIndentedString(processVariables)).append("\n");
    sb.append("    tenantId: ").append(toIndentedString(tenantId)).append("\n");
    sb.append("    tenantIdLike: ").append(toIndentedString(tenantIdLike)).append("\n");
    sb.append("    withoutTenantId: ").append(toIndentedString(withoutTenantId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

