/**
 * 工作流接口文档
 * 工作流接口文档
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.chinacreator.c2.flow.rest.model;

import java.util.Objects;
import com.chinacreator.c2.flow.rest.model.WfRestVariable;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;


/**
 * 历史任务信息
 */
@ApiModel(description = "历史任务信息")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-12-28T13:50:28.213+08:00")
public class WfHistoricTaskInstanceResponse   {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("processDefinitionId")
  private String processDefinitionId = null;

  @JsonProperty("processInstanceId")
  private String processInstanceId = null;

  @JsonProperty("executionId")
  private String executionId = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("deleteReason")
  private String deleteReason = null;

  @JsonProperty("owner")
  private String owner = null;

  @JsonProperty("assignee")
  private String assignee = null;

  @JsonProperty("startTime")
  private Date startTime = null;

  @JsonProperty("endTime")
  private Date endTime = null;

  @JsonProperty("durationInMillis")
  private Long durationInMillis = null;

  @JsonProperty("workTimeInMillis")
  private Long workTimeInMillis = null;

  @JsonProperty("claimTime")
  private Date claimTime = null;

  @JsonProperty("taskDefinitionKey")
  private String taskDefinitionKey = null;

  @JsonProperty("formKey")
  private String formKey = null;

  @JsonProperty("priority")
  private Integer priority = null;

  @JsonProperty("dueDate")
  private Date dueDate = null;

  @JsonProperty("parentTaskId")
  private String parentTaskId = null;

  @JsonProperty("variables")
  private List<WfRestVariable> variables = new ArrayList<WfRestVariable>();

  @JsonProperty("tenantId")
  private String tenantId = null;

  @JsonProperty("category")
  private String category = null;

  public WfHistoricTaskInstanceResponse id(String id) {
    this.id = id;
    return this;
  }

   /**
   * 任务id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "任务id")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public WfHistoricTaskInstanceResponse processDefinitionId(String processDefinitionId) {
    this.processDefinitionId = processDefinitionId;
    return this;
  }

   /**
   * 任务所在流程定义id
   * @return processDefinitionId
  **/
  @ApiModelProperty(example = "null", value = "任务所在流程定义id")
  public String getProcessDefinitionId() {
    return processDefinitionId;
  }

  public void setProcessDefinitionId(String processDefinitionId) {
    this.processDefinitionId = processDefinitionId;
  }

  public WfHistoricTaskInstanceResponse processInstanceId(String processInstanceId) {
    this.processInstanceId = processInstanceId;
    return this;
  }

   /**
   * 任务所在流程实例id
   * @return processInstanceId
  **/
  @ApiModelProperty(example = "null", value = "任务所在流程实例id")
  public String getProcessInstanceId() {
    return processInstanceId;
  }

  public void setProcessInstanceId(String processInstanceId) {
    this.processInstanceId = processInstanceId;
  }

  public WfHistoricTaskInstanceResponse executionId(String executionId) {
    this.executionId = executionId;
    return this;
  }

   /**
   * 任务执行id
   * @return executionId
  **/
  @ApiModelProperty(example = "null", value = "任务执行id")
  public String getExecutionId() {
    return executionId;
  }

  public void setExecutionId(String executionId) {
    this.executionId = executionId;
  }

  public WfHistoricTaskInstanceResponse name(String name) {
    this.name = name;
    return this;
  }

   /**
   * 任务名称
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "任务名称")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public WfHistoricTaskInstanceResponse description(String description) {
    this.description = description;
    return this;
  }

   /**
   * 任务描述
   * @return description
  **/
  @ApiModelProperty(example = "null", value = "任务描述")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public WfHistoricTaskInstanceResponse deleteReason(String deleteReason) {
    this.deleteReason = deleteReason;
    return this;
  }

   /**
   * 任务删除原因
   * @return deleteReason
  **/
  @ApiModelProperty(example = "null", value = "任务删除原因")
  public String getDeleteReason() {
    return deleteReason;
  }

  public void setDeleteReason(String deleteReason) {
    this.deleteReason = deleteReason;
  }

  public WfHistoricTaskInstanceResponse owner(String owner) {
    this.owner = owner;
    return this;
  }

   /**
   * 任务所有者
   * @return owner
  **/
  @ApiModelProperty(example = "null", value = "任务所有者")
  public String getOwner() {
    return owner;
  }

  public void setOwner(String owner) {
    this.owner = owner;
  }

  public WfHistoricTaskInstanceResponse assignee(String assignee) {
    this.assignee = assignee;
    return this;
  }

   /**
   * 任务处理人
   * @return assignee
  **/
  @ApiModelProperty(example = "null", value = "任务处理人")
  public String getAssignee() {
    return assignee;
  }

  public void setAssignee(String assignee) {
    this.assignee = assignee;
  }

  public WfHistoricTaskInstanceResponse startTime(Date startTime) {
    this.startTime = startTime;
    return this;
  }

   /**
   * 任务开始时间
   * @return startTime
  **/
  @ApiModelProperty(example = "null", value = "任务开始时间")
  public Date getStartTime() {
    return startTime;
  }

  public void setStartTime(Date startTime) {
    this.startTime = startTime;
  }

  public WfHistoricTaskInstanceResponse endTime(Date endTime) {
    this.endTime = endTime;
    return this;
  }

   /**
   * 任务结束时间
   * @return endTime
  **/
  @ApiModelProperty(example = "null", value = "任务结束时间")
  public Date getEndTime() {
    return endTime;
  }

  public void setEndTime(Date endTime) {
    this.endTime = endTime;
  }

  public WfHistoricTaskInstanceResponse durationInMillis(Long durationInMillis) {
    this.durationInMillis = durationInMillis;
    return this;
  }

   /**
   * 任务花费毫秒数
   * @return durationInMillis
  **/
  @ApiModelProperty(example = "null", value = "任务花费毫秒数")
  public Long getDurationInMillis() {
    return durationInMillis;
  }

  public void setDurationInMillis(Long durationInMillis) {
    this.durationInMillis = durationInMillis;
  }

  public WfHistoricTaskInstanceResponse workTimeInMillis(Long workTimeInMillis) {
    this.workTimeInMillis = workTimeInMillis;
    return this;
  }

   /**
   * 任务花费毫秒数
   * @return workTimeInMillis
  **/
  @ApiModelProperty(example = "null", value = "任务花费毫秒数")
  public Long getWorkTimeInMillis() {
    return workTimeInMillis;
  }

  public void setWorkTimeInMillis(Long workTimeInMillis) {
    this.workTimeInMillis = workTimeInMillis;
  }

  public WfHistoricTaskInstanceResponse claimTime(Date claimTime) {
    this.claimTime = claimTime;
    return this;
  }

   /**
   * 任务签收时间
   * @return claimTime
  **/
  @ApiModelProperty(example = "null", value = "任务签收时间")
  public Date getClaimTime() {
    return claimTime;
  }

  public void setClaimTime(Date claimTime) {
    this.claimTime = claimTime;
  }

  public WfHistoricTaskInstanceResponse taskDefinitionKey(String taskDefinitionKey) {
    this.taskDefinitionKey = taskDefinitionKey;
    return this;
  }

   /**
   * 任务所在环节定义key
   * @return taskDefinitionKey
  **/
  @ApiModelProperty(example = "null", value = "任务所在环节定义key")
  public String getTaskDefinitionKey() {
    return taskDefinitionKey;
  }

  public void setTaskDefinitionKey(String taskDefinitionKey) {
    this.taskDefinitionKey = taskDefinitionKey;
  }

  public WfHistoricTaskInstanceResponse formKey(String formKey) {
    this.formKey = formKey;
    return this;
  }

   /**
   * 任务表单key
   * @return formKey
  **/
  @ApiModelProperty(example = "null", value = "任务表单key")
  public String getFormKey() {
    return formKey;
  }

  public void setFormKey(String formKey) {
    this.formKey = formKey;
  }

  public WfHistoricTaskInstanceResponse priority(Integer priority) {
    this.priority = priority;
    return this;
  }

   /**
   * 任务优先级
   * @return priority
  **/
  @ApiModelProperty(example = "null", value = "任务优先级")
  public Integer getPriority() {
    return priority;
  }

  public void setPriority(Integer priority) {
    this.priority = priority;
  }

  public WfHistoricTaskInstanceResponse dueDate(Date dueDate) {
    this.dueDate = dueDate;
    return this;
  }

   /**
   * 任务过期时间
   * @return dueDate
  **/
  @ApiModelProperty(example = "null", value = "任务过期时间")
  public Date getDueDate() {
    return dueDate;
  }

  public void setDueDate(Date dueDate) {
    this.dueDate = dueDate;
  }

  public WfHistoricTaskInstanceResponse parentTaskId(String parentTaskId) {
    this.parentTaskId = parentTaskId;
    return this;
  }

   /**
   * 父任务id
   * @return parentTaskId
  **/
  @ApiModelProperty(example = "null", value = "父任务id")
  public String getParentTaskId() {
    return parentTaskId;
  }

  public void setParentTaskId(String parentTaskId) {
    this.parentTaskId = parentTaskId;
  }

  public WfHistoricTaskInstanceResponse variables(List<WfRestVariable> variables) {
    this.variables = variables;
    return this;
  }

  public WfHistoricTaskInstanceResponse addVariablesItem(WfRestVariable variablesItem) {
    this.variables.add(variablesItem);
    return this;
  }

   /**
   * 任务自定义变量集合
   * @return variables
  **/
  @ApiModelProperty(example = "null", value = "任务自定义变量集合")
  public List<WfRestVariable> getVariables() {
    return variables;
  }

  public void setVariables(List<WfRestVariable> variables) {
    this.variables = variables;
  }

  public WfHistoricTaskInstanceResponse tenantId(String tenantId) {
    this.tenantId = tenantId;
    return this;
  }

   /**
   * 租户
   * @return tenantId
  **/
  @ApiModelProperty(example = "null", value = "租户")
  public String getTenantId() {
    return tenantId;
  }

  public void setTenantId(String tenantId) {
    this.tenantId = tenantId;
  }

  public WfHistoricTaskInstanceResponse category(String category) {
    this.category = category;
    return this;
  }

   /**
   * 业务类别
   * @return category
  **/
  @ApiModelProperty(example = "null", value = "业务类别")
  public String getCategory() {
    return category;
  }

  public void setCategory(String category) {
    this.category = category;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WfHistoricTaskInstanceResponse wfHistoricTaskInstanceResponse = (WfHistoricTaskInstanceResponse) o;
    return Objects.equals(this.id, wfHistoricTaskInstanceResponse.id) &&
        Objects.equals(this.processDefinitionId, wfHistoricTaskInstanceResponse.processDefinitionId) &&
        Objects.equals(this.processInstanceId, wfHistoricTaskInstanceResponse.processInstanceId) &&
        Objects.equals(this.executionId, wfHistoricTaskInstanceResponse.executionId) &&
        Objects.equals(this.name, wfHistoricTaskInstanceResponse.name) &&
        Objects.equals(this.description, wfHistoricTaskInstanceResponse.description) &&
        Objects.equals(this.deleteReason, wfHistoricTaskInstanceResponse.deleteReason) &&
        Objects.equals(this.owner, wfHistoricTaskInstanceResponse.owner) &&
        Objects.equals(this.assignee, wfHistoricTaskInstanceResponse.assignee) &&
        Objects.equals(this.startTime, wfHistoricTaskInstanceResponse.startTime) &&
        Objects.equals(this.endTime, wfHistoricTaskInstanceResponse.endTime) &&
        Objects.equals(this.durationInMillis, wfHistoricTaskInstanceResponse.durationInMillis) &&
        Objects.equals(this.workTimeInMillis, wfHistoricTaskInstanceResponse.workTimeInMillis) &&
        Objects.equals(this.claimTime, wfHistoricTaskInstanceResponse.claimTime) &&
        Objects.equals(this.taskDefinitionKey, wfHistoricTaskInstanceResponse.taskDefinitionKey) &&
        Objects.equals(this.formKey, wfHistoricTaskInstanceResponse.formKey) &&
        Objects.equals(this.priority, wfHistoricTaskInstanceResponse.priority) &&
        Objects.equals(this.dueDate, wfHistoricTaskInstanceResponse.dueDate) &&
        Objects.equals(this.parentTaskId, wfHistoricTaskInstanceResponse.parentTaskId) &&
        Objects.equals(this.variables, wfHistoricTaskInstanceResponse.variables) &&
        Objects.equals(this.tenantId, wfHistoricTaskInstanceResponse.tenantId) &&
        Objects.equals(this.category, wfHistoricTaskInstanceResponse.category);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, processDefinitionId, processInstanceId, executionId, name, description, deleteReason, owner, assignee, startTime, endTime, durationInMillis, workTimeInMillis, claimTime, taskDefinitionKey, formKey, priority, dueDate, parentTaskId, variables, tenantId, category);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WfHistoricTaskInstanceResponse {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    processDefinitionId: ").append(toIndentedString(processDefinitionId)).append("\n");
    sb.append("    processInstanceId: ").append(toIndentedString(processInstanceId)).append("\n");
    sb.append("    executionId: ").append(toIndentedString(executionId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    deleteReason: ").append(toIndentedString(deleteReason)).append("\n");
    sb.append("    owner: ").append(toIndentedString(owner)).append("\n");
    sb.append("    assignee: ").append(toIndentedString(assignee)).append("\n");
    sb.append("    startTime: ").append(toIndentedString(startTime)).append("\n");
    sb.append("    endTime: ").append(toIndentedString(endTime)).append("\n");
    sb.append("    durationInMillis: ").append(toIndentedString(durationInMillis)).append("\n");
    sb.append("    workTimeInMillis: ").append(toIndentedString(workTimeInMillis)).append("\n");
    sb.append("    claimTime: ").append(toIndentedString(claimTime)).append("\n");
    sb.append("    taskDefinitionKey: ").append(toIndentedString(taskDefinitionKey)).append("\n");
    sb.append("    formKey: ").append(toIndentedString(formKey)).append("\n");
    sb.append("    priority: ").append(toIndentedString(priority)).append("\n");
    sb.append("    dueDate: ").append(toIndentedString(dueDate)).append("\n");
    sb.append("    parentTaskId: ").append(toIndentedString(parentTaskId)).append("\n");
    sb.append("    variables: ").append(toIndentedString(variables)).append("\n");
    sb.append("    tenantId: ").append(toIndentedString(tenantId)).append("\n");
    sb.append("    category: ").append(toIndentedString(category)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

