/**
 * 工作流接口文档
 * 工作流接口文档
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.chinacreator.c2.flow.rest.model;

import java.util.Objects;
import com.chinacreator.c2.flow.rest.model.WfRestVariable;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;


/**
 * 流程跳转入参
 */
@ApiModel(description = "流程跳转入参")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-12-28T13:50:28.213+08:00")
public class WfJumpRequest   {
  @JsonProperty("currentLoginUserId")
  private String currentLoginUserId = null;

  @JsonProperty("processInstanceId")
  private String processInstanceId = null;

  @JsonProperty("destTaskDefinitionKey")
  private String destTaskDefinitionKey = null;

  @JsonProperty("variables")
  private List<WfRestVariable> variables = new ArrayList<WfRestVariable>();

  public WfJumpRequest currentLoginUserId(String currentLoginUserId) {
    this.currentLoginUserId = currentLoginUserId;
    return this;
  }

   /**
   * 模拟当前登陆用户，需要后台启用开关(当流程独立部署且未集成sso环境时调试使用)
   * @return currentLoginUserId
  **/
  @ApiModelProperty(example = "null", value = "模拟当前登陆用户，需要后台启用开关(当流程独立部署且未集成sso环境时调试使用)")
  public String getCurrentLoginUserId() {
    return currentLoginUserId;
  }

  public void setCurrentLoginUserId(String currentLoginUserId) {
    this.currentLoginUserId = currentLoginUserId;
  }

  public WfJumpRequest processInstanceId(String processInstanceId) {
    this.processInstanceId = processInstanceId;
    return this;
  }

   /**
   * 流程实例id
   * @return processInstanceId
  **/
  @ApiModelProperty(example = "null", value = "流程实例id")
  public String getProcessInstanceId() {
    return processInstanceId;
  }

  public void setProcessInstanceId(String processInstanceId) {
    this.processInstanceId = processInstanceId;
  }

  public WfJumpRequest destTaskDefinitionKey(String destTaskDefinitionKey) {
    this.destTaskDefinitionKey = destTaskDefinitionKey;
    return this;
  }

   /**
   * 目标环节key
   * @return destTaskDefinitionKey
  **/
  @ApiModelProperty(example = "null", value = "目标环节key")
  public String getDestTaskDefinitionKey() {
    return destTaskDefinitionKey;
  }

  public void setDestTaskDefinitionKey(String destTaskDefinitionKey) {
    this.destTaskDefinitionKey = destTaskDefinitionKey;
  }

  public WfJumpRequest variables(List<WfRestVariable> variables) {
    this.variables = variables;
    return this;
  }

  public WfJumpRequest addVariablesItem(WfRestVariable variablesItem) {
    this.variables.add(variablesItem);
    return this;
  }

   /**
   * 流程变量
   * @return variables
  **/
  @ApiModelProperty(example = "null", value = "流程变量")
  public List<WfRestVariable> getVariables() {
    return variables;
  }

  public void setVariables(List<WfRestVariable> variables) {
    this.variables = variables;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WfJumpRequest wfJumpRequest = (WfJumpRequest) o;
    return Objects.equals(this.currentLoginUserId, wfJumpRequest.currentLoginUserId) &&
        Objects.equals(this.processInstanceId, wfJumpRequest.processInstanceId) &&
        Objects.equals(this.destTaskDefinitionKey, wfJumpRequest.destTaskDefinitionKey) &&
        Objects.equals(this.variables, wfJumpRequest.variables);
  }

  @Override
  public int hashCode() {
    return Objects.hash(currentLoginUserId, processInstanceId, destTaskDefinitionKey, variables);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WfJumpRequest {\n");
    
    sb.append("    currentLoginUserId: ").append(toIndentedString(currentLoginUserId)).append("\n");
    sb.append("    processInstanceId: ").append(toIndentedString(processInstanceId)).append("\n");
    sb.append("    destTaskDefinitionKey: ").append(toIndentedString(destTaskDefinitionKey)).append("\n");
    sb.append("    variables: ").append(toIndentedString(variables)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

