/**
 * 工作流接口文档
 * 工作流接口文档
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.chinacreator.c2.flow.rest.model;

import java.util.Objects;
import com.chinacreator.c2.flow.rest.model.WfRestVariable;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

import java.io.Serializable;
/**
 * 流程实例信息
 */
@ApiModel(description = "流程实例信息")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-12-28T16:50:41.068+08:00")
public class WfProcessInstanceResponse  implements Serializable {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("businessKey")
  private String businessKey = null;

  @JsonProperty("suspended")
  private Boolean suspended = null;

  @JsonProperty("processDefinitionId")
  private String processDefinitionId = null;

  @JsonProperty("activityId")
  private String activityId = null;

  @JsonProperty("variables")
  private List<WfRestVariable> variables = new ArrayList<WfRestVariable>();

  @JsonProperty("tenantId")
  private String tenantId = null;

  public WfProcessInstanceResponse id(String id) {
    this.id = id;
    return this;
  }

   /**
   * 流程实例id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "流程实例id")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public WfProcessInstanceResponse businessKey(String businessKey) {
    this.businessKey = businessKey;
    return this;
  }

   /**
   * 业务主键
   * @return businessKey
  **/
  @ApiModelProperty(example = "null", value = "业务主键")
  public String getBusinessKey() {
    return businessKey;
  }

  public void setBusinessKey(String businessKey) {
    this.businessKey = businessKey;
  }

  public WfProcessInstanceResponse suspended(Boolean suspended) {
    this.suspended = suspended;
    return this;
  }

   /**
   * 流程实例是否挂起
   * @return suspended
  **/
  @ApiModelProperty(example = "null", value = "流程实例是否挂起")
  public Boolean getSuspended() {
    return suspended;
  }

  public void setSuspended(Boolean suspended) {
    this.suspended = suspended;
  }

  public WfProcessInstanceResponse processDefinitionId(String processDefinitionId) {
    this.processDefinitionId = processDefinitionId;
    return this;
  }

   /**
   * 流程定义id
   * @return processDefinitionId
  **/
  @ApiModelProperty(example = "null", value = "流程定义id")
  public String getProcessDefinitionId() {
    return processDefinitionId;
  }

  public void setProcessDefinitionId(String processDefinitionId) {
    this.processDefinitionId = processDefinitionId;
  }

  public WfProcessInstanceResponse activityId(String activityId) {
    this.activityId = activityId;
    return this;
  }

   /**
   * 活动id
   * @return activityId
  **/
  @ApiModelProperty(example = "null", value = "活动id")
  public String getActivityId() {
    return activityId;
  }

  public void setActivityId(String activityId) {
    this.activityId = activityId;
  }

  public WfProcessInstanceResponse variables(List<WfRestVariable> variables) {
    this.variables = variables;
    return this;
  }

  public WfProcessInstanceResponse addVariablesItem(WfRestVariable variablesItem) {
    this.variables.add(variablesItem);
    return this;
  }

   /**
   * 流程实例的自定义变量集合
   * @return variables
  **/
  @ApiModelProperty(example = "null", value = "流程实例的自定义变量集合")
  public List<WfRestVariable> getVariables() {
    return variables;
  }

  public void setVariables(List<WfRestVariable> variables) {
    this.variables = variables;
  }

  public WfProcessInstanceResponse tenantId(String tenantId) {
    this.tenantId = tenantId;
    return this;
  }

   /**
   * 租户
   * @return tenantId
  **/
  @ApiModelProperty(example = "null", value = "租户")
  public String getTenantId() {
    return tenantId;
  }

  public void setTenantId(String tenantId) {
    this.tenantId = tenantId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WfProcessInstanceResponse wfProcessInstanceResponse = (WfProcessInstanceResponse) o;
    return Objects.equals(this.id, wfProcessInstanceResponse.id) &&
        Objects.equals(this.businessKey, wfProcessInstanceResponse.businessKey) &&
        Objects.equals(this.suspended, wfProcessInstanceResponse.suspended) &&
        Objects.equals(this.processDefinitionId, wfProcessInstanceResponse.processDefinitionId) &&
        Objects.equals(this.activityId, wfProcessInstanceResponse.activityId) &&
        Objects.equals(this.variables, wfProcessInstanceResponse.variables) &&
        Objects.equals(this.tenantId, wfProcessInstanceResponse.tenantId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, businessKey, suspended, processDefinitionId, activityId, variables, tenantId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WfProcessInstanceResponse {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    businessKey: ").append(toIndentedString(businessKey)).append("\n");
    sb.append("    suspended: ").append(toIndentedString(suspended)).append("\n");
    sb.append("    processDefinitionId: ").append(toIndentedString(processDefinitionId)).append("\n");
    sb.append("    activityId: ").append(toIndentedString(activityId)).append("\n");
    sb.append("    variables: ").append(toIndentedString(variables)).append("\n");
    sb.append("    tenantId: ").append(toIndentedString(tenantId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

