/**
 * 工作流接口文档
 * 工作流接口文档
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.chinacreator.c2.flow.rest.model;

import java.util.Objects;
import com.chinacreator.c2.flow.rest.model.WfBusinessDataRequest;
import com.chinacreator.c2.flow.rest.model.WfRestVariable;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;


/**
 * 创建流程实例入参
 */
@ApiModel(description = "创建流程实例入参")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-12-15T15:13:20.386+08:00")
public class WfProcessInstanceCreateRequest   {
  @JsonProperty("currentLoginUserId")
  private String currentLoginUserId = null;

  @JsonProperty("businessData")
  private WfBusinessDataRequest businessData = null;

  @JsonProperty("processDefinitionId")
  private String processDefinitionId = null;

  @JsonProperty("processDefinitionKey")
  private String processDefinitionKey = null;

  @JsonProperty("variables")
  private List<WfRestVariable> variables = new ArrayList<WfRestVariable>();

  @JsonProperty("tenantId")
  private String tenantId = null;

  public WfProcessInstanceCreateRequest currentLoginUserId(String currentLoginUserId) {
    this.currentLoginUserId = currentLoginUserId;
    return this;
  }

   /**
   * 模拟当前登陆用户，需要后台启用开关(当流程独立部署且未集成sso环境时调试使用)
   * @return currentLoginUserId
  **/
  @ApiModelProperty(example = "null", value = "模拟当前登陆用户，需要后台启用开关(当流程独立部署且未集成sso环境时调试使用)")
  public String getCurrentLoginUserId() {
    return currentLoginUserId;
  }

  public void setCurrentLoginUserId(String currentLoginUserId) {
    this.currentLoginUserId = currentLoginUserId;
  }

  public WfProcessInstanceCreateRequest businessData(WfBusinessDataRequest businessData) {
    this.businessData = businessData;
    return this;
  }

   /**
   * Get businessData
   * @return businessData
  **/
  @ApiModelProperty(example = "null", value = "")
  public WfBusinessDataRequest getBusinessData() {
    return businessData;
  }

  public void setBusinessData(WfBusinessDataRequest businessData) {
    this.businessData = businessData;
  }

  public WfProcessInstanceCreateRequest processDefinitionId(String processDefinitionId) {
    this.processDefinitionId = processDefinitionId;
    return this;
  }

   /**
   * 根据流程定义id来启动流程，此时不再传processDefinitionKey
   * @return processDefinitionId
  **/
  @ApiModelProperty(example = "null", value = "根据流程定义id来启动流程，此时不再传processDefinitionKey")
  public String getProcessDefinitionId() {
    return processDefinitionId;
  }

  public void setProcessDefinitionId(String processDefinitionId) {
    this.processDefinitionId = processDefinitionId;
  }

  public WfProcessInstanceCreateRequest processDefinitionKey(String processDefinitionKey) {
    this.processDefinitionKey = processDefinitionKey;
    return this;
  }

   /**
   * 根据流程定义key来启动流程(自动使用最新版本)，此时不再传processDefinitionId
   * @return processDefinitionKey
  **/
  @ApiModelProperty(example = "null", value = "根据流程定义key来启动流程(自动使用最新版本)，此时不再传processDefinitionId")
  public String getProcessDefinitionKey() {
    return processDefinitionKey;
  }

  public void setProcessDefinitionKey(String processDefinitionKey) {
    this.processDefinitionKey = processDefinitionKey;
  }

  public WfProcessInstanceCreateRequest variables(List<WfRestVariable> variables) {
    this.variables = variables;
    return this;
  }

  public WfProcessInstanceCreateRequest addVariablesItem(WfRestVariable variablesItem) {
    this.variables.add(variablesItem);
    return this;
  }

   /**
   * 启动流程需要的自定义变量
   * @return variables
  **/
  @ApiModelProperty(example = "null", value = "启动流程需要的自定义变量")
  public List<WfRestVariable> getVariables() {
    return variables;
  }

  public void setVariables(List<WfRestVariable> variables) {
    this.variables = variables;
  }

  public WfProcessInstanceCreateRequest tenantId(String tenantId) {
    this.tenantId = tenantId;
    return this;
  }

   /**
   * 租户
   * @return tenantId
  **/
  @ApiModelProperty(example = "null", value = "租户")
  public String getTenantId() {
    return tenantId;
  }

  public void setTenantId(String tenantId) {
    this.tenantId = tenantId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WfProcessInstanceCreateRequest wfProcessInstanceCreateRequest = (WfProcessInstanceCreateRequest) o;
    return Objects.equals(this.currentLoginUserId, wfProcessInstanceCreateRequest.currentLoginUserId) &&
        Objects.equals(this.businessData, wfProcessInstanceCreateRequest.businessData) &&
        Objects.equals(this.processDefinitionId, wfProcessInstanceCreateRequest.processDefinitionId) &&
        Objects.equals(this.processDefinitionKey, wfProcessInstanceCreateRequest.processDefinitionKey) &&
        Objects.equals(this.variables, wfProcessInstanceCreateRequest.variables) &&
        Objects.equals(this.tenantId, wfProcessInstanceCreateRequest.tenantId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(currentLoginUserId, businessData, processDefinitionId, processDefinitionKey, variables, tenantId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WfProcessInstanceCreateRequest {\n");
    
    sb.append("    currentLoginUserId: ").append(toIndentedString(currentLoginUserId)).append("\n");
    sb.append("    businessData: ").append(toIndentedString(businessData)).append("\n");
    sb.append("    processDefinitionId: ").append(toIndentedString(processDefinitionId)).append("\n");
    sb.append("    processDefinitionKey: ").append(toIndentedString(processDefinitionKey)).append("\n");
    sb.append("    variables: ").append(toIndentedString(variables)).append("\n");
    sb.append("    tenantId: ").append(toIndentedString(tenantId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

