/**
 * 工作流接口文档
 * 工作流接口文档
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.chinacreator.c2.flow.rest.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * 流程变量
 */
@ApiModel(description = "流程变量")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-12-27T09:47:23.486+08:00")
public class WfRestVariable   {
  @JsonProperty("name")
  private String name = null;

  /**
   * 变量类型
   */
  public enum TypeEnum {
    STRING("string"),
    
    BOOLEAN("boolean"),
    
    DATE("date"),
    
    DOUBLE("double"),
    
    INTEGER("integer"),
    
    LONG("long"),
    
    SHORT("short"),
    
    JAVA_UTIL_LIST("java.util.List"),
    
    JAVA_UTIL_MAP("java.util.Map");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String text) {
      for (TypeEnum b : TypeEnum.values()) {
          if (String.valueOf(b.value).equals(text)) {
              return b;
          }
      }
      return null;
    }
  }

  @JsonProperty("type")
  private TypeEnum type = null;

  /**
   * 变量作用域
   */
  public enum VariableScopeEnum {
    LOCAL("LOCAL"),
    
    GLOBAL("GLOBAL");

    private String value;

    VariableScopeEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static VariableScopeEnum fromValue(String text) {
      for (VariableScopeEnum b : VariableScopeEnum.values()) {
          if (String.valueOf(b.value).equals(text)) {
              return b;
          }
      }
      return null;
    }
  }

  @JsonProperty("variableScope")
  private VariableScopeEnum variableScope = null;

  @JsonProperty("value")
  private Object value = null;

  public WfRestVariable name(String name) {
    this.name = name;
    return this;
  }

   /**
   * 变量名
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "变量名")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public WfRestVariable type(TypeEnum type) {
    this.type = type;
    return this;
  }

   /**
   * 变量类型
   * @return type
  **/
  @ApiModelProperty(example = "null", value = "变量类型")
  public TypeEnum getType() {
    return type;
  }

  public void setType(TypeEnum type) {
    this.type = type;
  }

  public WfRestVariable variableScope(VariableScopeEnum variableScope) {
    this.variableScope = variableScope;
    return this;
  }

   /**
   * 变量作用域
   * @return variableScope
  **/
  @ApiModelProperty(example = "null", value = "变量作用域")
  public VariableScopeEnum getVariableScope() {
    return variableScope;
  }

  public void setVariableScope(VariableScopeEnum variableScope) {
    this.variableScope = variableScope;
  }

  public WfRestVariable value(Object value) {
    this.value = value;
    return this;
  }

   /**
   * 变量值
   * @return value
  **/
  @ApiModelProperty(example = "null", value = "变量值")
  public Object getValue() {
    return value;
  }

  public void setValue(Object value) {
    this.value = value;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WfRestVariable wfRestVariable = (WfRestVariable) o;
    return Objects.equals(this.name, wfRestVariable.name) &&
        Objects.equals(this.type, wfRestVariable.type) &&
        Objects.equals(this.variableScope, wfRestVariable.variableScope) &&
        Objects.equals(this.value, wfRestVariable.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, type, variableScope, value);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WfRestVariable {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    variableScope: ").append(toIndentedString(variableScope)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

