/**
 * 工作流接口文档
 * 工作流接口文档
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.chinacreator.c2.flow.rest.model;

import java.util.Objects;
import com.chinacreator.c2.flow.rest.model.WfRestVariable;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;


/**
 * 任务信息
 */
@ApiModel(description = "任务信息")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-12-28T13:50:28.213+08:00")
public class WfTaskResponse   {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("owner")
  private String owner = null;

  @JsonProperty("assignee")
  private String assignee = null;

  @JsonProperty("delegationState")
  private String delegationState = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("createTime")
  private Date createTime = null;

  @JsonProperty("dueDate")
  private Date dueDate = null;

  @JsonProperty("priority")
  private Integer priority = null;

  @JsonProperty("suspended")
  private Boolean suspended = null;

  @JsonProperty("taskDefinitionKey")
  private String taskDefinitionKey = null;

  @JsonProperty("tenantId")
  private String tenantId = null;

  @JsonProperty("category")
  private String category = null;

  @JsonProperty("parentTaskId")
  private String parentTaskId = null;

  @JsonProperty("executionId")
  private String executionId = null;

  @JsonProperty("processInstanceId")
  private String processInstanceId = null;

  @JsonProperty("processDefinitionId")
  private String processDefinitionId = null;

  @JsonProperty("variables")
  private List<WfRestVariable> variables = new ArrayList<WfRestVariable>();

  public WfTaskResponse id(String id) {
    this.id = id;
    return this;
  }

   /**
   * 任务id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "任务id")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public WfTaskResponse owner(String owner) {
    this.owner = owner;
    return this;
  }

   /**
   * 任务所有者
   * @return owner
  **/
  @ApiModelProperty(example = "null", value = "任务所有者")
  public String getOwner() {
    return owner;
  }

  public void setOwner(String owner) {
    this.owner = owner;
  }

  public WfTaskResponse assignee(String assignee) {
    this.assignee = assignee;
    return this;
  }

   /**
   * 任务处理人
   * @return assignee
  **/
  @ApiModelProperty(example = "null", value = "任务处理人")
  public String getAssignee() {
    return assignee;
  }

  public void setAssignee(String assignee) {
    this.assignee = assignee;
  }

  public WfTaskResponse delegationState(String delegationState) {
    this.delegationState = delegationState;
    return this;
  }

   /**
   * 任务代理状态
   * @return delegationState
  **/
  @ApiModelProperty(example = "null", value = "任务代理状态")
  public String getDelegationState() {
    return delegationState;
  }

  public void setDelegationState(String delegationState) {
    this.delegationState = delegationState;
  }

  public WfTaskResponse name(String name) {
    this.name = name;
    return this;
  }

   /**
   * 任务名称
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "任务名称")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public WfTaskResponse description(String description) {
    this.description = description;
    return this;
  }

   /**
   * 任务描述
   * @return description
  **/
  @ApiModelProperty(example = "null", value = "任务描述")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public WfTaskResponse createTime(Date createTime) {
    this.createTime = createTime;
    return this;
  }

   /**
   * 任务创建时间
   * @return createTime
  **/
  @ApiModelProperty(example = "null", value = "任务创建时间")
  public Date getCreateTime() {
    return createTime;
  }

  public void setCreateTime(Date createTime) {
    this.createTime = createTime;
  }

  public WfTaskResponse dueDate(Date dueDate) {
    this.dueDate = dueDate;
    return this;
  }

   /**
   * 任务过期时间
   * @return dueDate
  **/
  @ApiModelProperty(example = "null", value = "任务过期时间")
  public Date getDueDate() {
    return dueDate;
  }

  public void setDueDate(Date dueDate) {
    this.dueDate = dueDate;
  }

  public WfTaskResponse priority(Integer priority) {
    this.priority = priority;
    return this;
  }

   /**
   * 任务优先级
   * @return priority
  **/
  @ApiModelProperty(example = "null", value = "任务优先级")
  public Integer getPriority() {
    return priority;
  }

  public void setPriority(Integer priority) {
    this.priority = priority;
  }

  public WfTaskResponse suspended(Boolean suspended) {
    this.suspended = suspended;
    return this;
  }

   /**
   * 任务是否挂起
   * @return suspended
  **/
  @ApiModelProperty(example = "null", value = "任务是否挂起")
  public Boolean getSuspended() {
    return suspended;
  }

  public void setSuspended(Boolean suspended) {
    this.suspended = suspended;
  }

  public WfTaskResponse taskDefinitionKey(String taskDefinitionKey) {
    this.taskDefinitionKey = taskDefinitionKey;
    return this;
  }

   /**
   * 任务环节定义key
   * @return taskDefinitionKey
  **/
  @ApiModelProperty(example = "null", value = "任务环节定义key")
  public String getTaskDefinitionKey() {
    return taskDefinitionKey;
  }

  public void setTaskDefinitionKey(String taskDefinitionKey) {
    this.taskDefinitionKey = taskDefinitionKey;
  }

  public WfTaskResponse tenantId(String tenantId) {
    this.tenantId = tenantId;
    return this;
  }

   /**
   * 租户
   * @return tenantId
  **/
  @ApiModelProperty(example = "null", value = "租户")
  public String getTenantId() {
    return tenantId;
  }

  public void setTenantId(String tenantId) {
    this.tenantId = tenantId;
  }

  public WfTaskResponse category(String category) {
    this.category = category;
    return this;
  }

   /**
   * 类别
   * @return category
  **/
  @ApiModelProperty(example = "null", value = "类别")
  public String getCategory() {
    return category;
  }

  public void setCategory(String category) {
    this.category = category;
  }

  public WfTaskResponse parentTaskId(String parentTaskId) {
    this.parentTaskId = parentTaskId;
    return this;
  }

   /**
   * 父任务id
   * @return parentTaskId
  **/
  @ApiModelProperty(example = "null", value = "父任务id")
  public String getParentTaskId() {
    return parentTaskId;
  }

  public void setParentTaskId(String parentTaskId) {
    this.parentTaskId = parentTaskId;
  }

  public WfTaskResponse executionId(String executionId) {
    this.executionId = executionId;
    return this;
  }

   /**
   * 任务执行id
   * @return executionId
  **/
  @ApiModelProperty(example = "null", value = "任务执行id")
  public String getExecutionId() {
    return executionId;
  }

  public void setExecutionId(String executionId) {
    this.executionId = executionId;
  }

  public WfTaskResponse processInstanceId(String processInstanceId) {
    this.processInstanceId = processInstanceId;
    return this;
  }

   /**
   * 任务所在流程实例id
   * @return processInstanceId
  **/
  @ApiModelProperty(example = "null", value = "任务所在流程实例id")
  public String getProcessInstanceId() {
    return processInstanceId;
  }

  public void setProcessInstanceId(String processInstanceId) {
    this.processInstanceId = processInstanceId;
  }

  public WfTaskResponse processDefinitionId(String processDefinitionId) {
    this.processDefinitionId = processDefinitionId;
    return this;
  }

   /**
   * 任务所在流程定义id
   * @return processDefinitionId
  **/
  @ApiModelProperty(example = "null", value = "任务所在流程定义id")
  public String getProcessDefinitionId() {
    return processDefinitionId;
  }

  public void setProcessDefinitionId(String processDefinitionId) {
    this.processDefinitionId = processDefinitionId;
  }

  public WfTaskResponse variables(List<WfRestVariable> variables) {
    this.variables = variables;
    return this;
  }

  public WfTaskResponse addVariablesItem(WfRestVariable variablesItem) {
    this.variables.add(variablesItem);
    return this;
  }

   /**
   * 当前任务的自定义变量集合
   * @return variables
  **/
  @ApiModelProperty(example = "null", value = "当前任务的自定义变量集合")
  public List<WfRestVariable> getVariables() {
    return variables;
  }

  public void setVariables(List<WfRestVariable> variables) {
    this.variables = variables;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WfTaskResponse wfTaskResponse = (WfTaskResponse) o;
    return Objects.equals(this.id, wfTaskResponse.id) &&
        Objects.equals(this.owner, wfTaskResponse.owner) &&
        Objects.equals(this.assignee, wfTaskResponse.assignee) &&
        Objects.equals(this.delegationState, wfTaskResponse.delegationState) &&
        Objects.equals(this.name, wfTaskResponse.name) &&
        Objects.equals(this.description, wfTaskResponse.description) &&
        Objects.equals(this.createTime, wfTaskResponse.createTime) &&
        Objects.equals(this.dueDate, wfTaskResponse.dueDate) &&
        Objects.equals(this.priority, wfTaskResponse.priority) &&
        Objects.equals(this.suspended, wfTaskResponse.suspended) &&
        Objects.equals(this.taskDefinitionKey, wfTaskResponse.taskDefinitionKey) &&
        Objects.equals(this.tenantId, wfTaskResponse.tenantId) &&
        Objects.equals(this.category, wfTaskResponse.category) &&
        Objects.equals(this.parentTaskId, wfTaskResponse.parentTaskId) &&
        Objects.equals(this.executionId, wfTaskResponse.executionId) &&
        Objects.equals(this.processInstanceId, wfTaskResponse.processInstanceId) &&
        Objects.equals(this.processDefinitionId, wfTaskResponse.processDefinitionId) &&
        Objects.equals(this.variables, wfTaskResponse.variables);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, owner, assignee, delegationState, name, description, createTime, dueDate, priority, suspended, taskDefinitionKey, tenantId, category, parentTaskId, executionId, processInstanceId, processDefinitionId, variables);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WfTaskResponse {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    owner: ").append(toIndentedString(owner)).append("\n");
    sb.append("    assignee: ").append(toIndentedString(assignee)).append("\n");
    sb.append("    delegationState: ").append(toIndentedString(delegationState)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    createTime: ").append(toIndentedString(createTime)).append("\n");
    sb.append("    dueDate: ").append(toIndentedString(dueDate)).append("\n");
    sb.append("    priority: ").append(toIndentedString(priority)).append("\n");
    sb.append("    suspended: ").append(toIndentedString(suspended)).append("\n");
    sb.append("    taskDefinitionKey: ").append(toIndentedString(taskDefinitionKey)).append("\n");
    sb.append("    tenantId: ").append(toIndentedString(tenantId)).append("\n");
    sb.append("    category: ").append(toIndentedString(category)).append("\n");
    sb.append("    parentTaskId: ").append(toIndentedString(parentTaskId)).append("\n");
    sb.append("    executionId: ").append(toIndentedString(executionId)).append("\n");
    sb.append("    processInstanceId: ").append(toIndentedString(processInstanceId)).append("\n");
    sb.append("    processDefinitionId: ").append(toIndentedString(processDefinitionId)).append("\n");
    sb.append("    variables: ").append(toIndentedString(variables)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

