/**
 * 工作流接口文档
 * 工作流接口文档
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.chinacreator.c2.flow.rest.model;

import java.util.Objects;
import com.chinacreator.c2.flow.rest.model.WfQueryVariable;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;


/**
 * 任务查询对象
 */
@ApiModel(description = "任务查询对象")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-12-27T09:47:23.486+08:00")
public class WfTaskQueryRequest   {
  @JsonProperty("start")
  private Integer start = null;

  @JsonProperty("size")
  private Integer size = null;

  @JsonProperty("sort")
  private String sort = null;

  @JsonProperty("order")
  private String order = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("nameLike")
  private String nameLike = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("descriptionLike")
  private String descriptionLike = null;

  @JsonProperty("priority")
  private Integer priority = null;

  @JsonProperty("minimumPriority")
  private Integer minimumPriority = null;

  @JsonProperty("maximumPriority")
  private Integer maximumPriority = null;

  @JsonProperty("assignee")
  private String assignee = null;

  @JsonProperty("assigneeLike")
  private String assigneeLike = null;

  @JsonProperty("owner")
  private String owner = null;

  @JsonProperty("ownerLike")
  private String ownerLike = null;

  @JsonProperty("unassigned")
  private Boolean unassigned = null;

  @JsonProperty("delegationState")
  private String delegationState = null;

  @JsonProperty("candidateUser")
  private String candidateUser = null;

  @JsonProperty("candidateGroupIn")
  private List<String> candidateGroupIn = new ArrayList<String>();

  @JsonProperty("candidateOrAssigned")
  private String candidateOrAssigned = null;

  @JsonProperty("involvedUser")
  private String involvedUser = null;

  @JsonProperty("processInstanceId")
  private String processInstanceId = null;

  @JsonProperty("processInstanceBusinessKey")
  private String processInstanceBusinessKey = null;

  @JsonProperty("processInstanceBusinessKeyLike")
  private String processInstanceBusinessKeyLike = null;

  @JsonProperty("processDefinitionKey")
  private String processDefinitionKey = null;

  @JsonProperty("processDefinitionName")
  private String processDefinitionName = null;

  @JsonProperty("processDefinitionKeyLike")
  private String processDefinitionKeyLike = null;

  @JsonProperty("processDefinitionNameLike")
  private String processDefinitionNameLike = null;

  @JsonProperty("executionId")
  private String executionId = null;

  @JsonProperty("createdOn")
  private Date createdOn = null;

  @JsonProperty("createdBefore")
  private Date createdBefore = null;

  @JsonProperty("createdAfter")
  private Date createdAfter = null;

  @JsonProperty("excludeSubTasks")
  private Boolean excludeSubTasks = null;

  @JsonProperty("taskDefinitionKey")
  private String taskDefinitionKey = null;

  @JsonProperty("taskDefinitionKeyLike")
  private String taskDefinitionKeyLike = null;

  @JsonProperty("dueDate")
  private Date dueDate = null;

  @JsonProperty("dueBefore")
  private Date dueBefore = null;

  @JsonProperty("dueAfter")
  private Date dueAfter = null;

  @JsonProperty("withoutDueDate")
  private Boolean withoutDueDate = null;

  @JsonProperty("active")
  private Boolean active = null;

  @JsonProperty("includeTaskLocalVariables")
  private Boolean includeTaskLocalVariables = null;

  @JsonProperty("includeProcessVariables")
  private Boolean includeProcessVariables = null;

  @JsonProperty("tenantId")
  private String tenantId = null;

  @JsonProperty("tenantIdLike")
  private String tenantIdLike = null;

  @JsonProperty("withoutTenantId")
  private Boolean withoutTenantId = null;

  @JsonProperty("taskVariables")
  private List<WfQueryVariable> taskVariables = new ArrayList<WfQueryVariable>();

  @JsonProperty("processInstanceVariables")
  private List<WfQueryVariable> processInstanceVariables = new ArrayList<WfQueryVariable>();

  public WfTaskQueryRequest start(Integer start) {
    this.start = start;
    return this;
  }

   /**
   * 开始行
   * @return start
  **/
  @ApiModelProperty(example = "null", value = "开始行")
  public Integer getStart() {
    return start;
  }

  public void setStart(Integer start) {
    this.start = start;
  }

  public WfTaskQueryRequest size(Integer size) {
    this.size = size;
    return this;
  }

   /**
   * 请求大小
   * @return size
  **/
  @ApiModelProperty(example = "null", value = "请求大小")
  public Integer getSize() {
    return size;
  }

  public void setSize(Integer size) {
    this.size = size;
  }

  public WfTaskQueryRequest sort(String sort) {
    this.sort = sort;
    return this;
  }

   /**
   * 排序字段
   * @return sort
  **/
  @ApiModelProperty(example = "null", value = "排序字段")
  public String getSort() {
    return sort;
  }

  public void setSort(String sort) {
    this.sort = sort;
  }

  public WfTaskQueryRequest order(String order) {
    this.order = order;
    return this;
  }

   /**
   * 排序方式asc/desc
   * @return order
  **/
  @ApiModelProperty(example = "null", value = "排序方式asc/desc")
  public String getOrder() {
    return order;
  }

  public void setOrder(String order) {
    this.order = order;
  }

  public WfTaskQueryRequest name(String name) {
    this.name = name;
    return this;
  }

   /**
   * 任务名称
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "任务名称")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public WfTaskQueryRequest nameLike(String nameLike) {
    this.nameLike = nameLike;
    return this;
  }

   /**
   * 任务名称模糊条件
   * @return nameLike
  **/
  @ApiModelProperty(example = "null", value = "任务名称模糊条件")
  public String getNameLike() {
    return nameLike;
  }

  public void setNameLike(String nameLike) {
    this.nameLike = nameLike;
  }

  public WfTaskQueryRequest description(String description) {
    this.description = description;
    return this;
  }

   /**
   * 任务描述
   * @return description
  **/
  @ApiModelProperty(example = "null", value = "任务描述")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public WfTaskQueryRequest descriptionLike(String descriptionLike) {
    this.descriptionLike = descriptionLike;
    return this;
  }

   /**
   * 任务描述模糊条件
   * @return descriptionLike
  **/
  @ApiModelProperty(example = "null", value = "任务描述模糊条件")
  public String getDescriptionLike() {
    return descriptionLike;
  }

  public void setDescriptionLike(String descriptionLike) {
    this.descriptionLike = descriptionLike;
  }

  public WfTaskQueryRequest priority(Integer priority) {
    this.priority = priority;
    return this;
  }

   /**
   * 任务优先级
   * @return priority
  **/
  @ApiModelProperty(example = "null", value = "任务优先级")
  public Integer getPriority() {
    return priority;
  }

  public void setPriority(Integer priority) {
    this.priority = priority;
  }

  public WfTaskQueryRequest minimumPriority(Integer minimumPriority) {
    this.minimumPriority = minimumPriority;
    return this;
  }

   /**
   * 任务优先级下区间
   * @return minimumPriority
  **/
  @ApiModelProperty(example = "null", value = "任务优先级下区间")
  public Integer getMinimumPriority() {
    return minimumPriority;
  }

  public void setMinimumPriority(Integer minimumPriority) {
    this.minimumPriority = minimumPriority;
  }

  public WfTaskQueryRequest maximumPriority(Integer maximumPriority) {
    this.maximumPriority = maximumPriority;
    return this;
  }

   /**
   * 任务优先级上区间
   * @return maximumPriority
  **/
  @ApiModelProperty(example = "null", value = "任务优先级上区间")
  public Integer getMaximumPriority() {
    return maximumPriority;
  }

  public void setMaximumPriority(Integer maximumPriority) {
    this.maximumPriority = maximumPriority;
  }

  public WfTaskQueryRequest assignee(String assignee) {
    this.assignee = assignee;
    return this;
  }

   /**
   * 处理人
   * @return assignee
  **/
  @ApiModelProperty(example = "null", value = "处理人")
  public String getAssignee() {
    return assignee;
  }

  public void setAssignee(String assignee) {
    this.assignee = assignee;
  }

  public WfTaskQueryRequest assigneeLike(String assigneeLike) {
    this.assigneeLike = assigneeLike;
    return this;
  }

   /**
   * 处理人模糊条件
   * @return assigneeLike
  **/
  @ApiModelProperty(example = "null", value = "处理人模糊条件")
  public String getAssigneeLike() {
    return assigneeLike;
  }

  public void setAssigneeLike(String assigneeLike) {
    this.assigneeLike = assigneeLike;
  }

  public WfTaskQueryRequest owner(String owner) {
    this.owner = owner;
    return this;
  }

   /**
   * 任务所有者
   * @return owner
  **/
  @ApiModelProperty(example = "null", value = "任务所有者")
  public String getOwner() {
    return owner;
  }

  public void setOwner(String owner) {
    this.owner = owner;
  }

  public WfTaskQueryRequest ownerLike(String ownerLike) {
    this.ownerLike = ownerLike;
    return this;
  }

   /**
   * 任务所有者模糊条件
   * @return ownerLike
  **/
  @ApiModelProperty(example = "null", value = "任务所有者模糊条件")
  public String getOwnerLike() {
    return ownerLike;
  }

  public void setOwnerLike(String ownerLike) {
    this.ownerLike = ownerLike;
  }

  public WfTaskQueryRequest unassigned(Boolean unassigned) {
    this.unassigned = unassigned;
    return this;
  }

   /**
   * 任务是否未分配
   * @return unassigned
  **/
  @ApiModelProperty(example = "null", value = "任务是否未分配")
  public Boolean getUnassigned() {
    return unassigned;
  }

  public void setUnassigned(Boolean unassigned) {
    this.unassigned = unassigned;
  }

  public WfTaskQueryRequest delegationState(String delegationState) {
    this.delegationState = delegationState;
    return this;
  }

   /**
   * 代理状态
   * @return delegationState
  **/
  @ApiModelProperty(example = "null", value = "代理状态")
  public String getDelegationState() {
    return delegationState;
  }

  public void setDelegationState(String delegationState) {
    this.delegationState = delegationState;
  }

  public WfTaskQueryRequest candidateUser(String candidateUser) {
    this.candidateUser = candidateUser;
    return this;
  }

   /**
   * 候选人
   * @return candidateUser
  **/
  @ApiModelProperty(example = "null", value = "候选人")
  public String getCandidateUser() {
    return candidateUser;
  }

  public void setCandidateUser(String candidateUser) {
    this.candidateUser = candidateUser;
  }

  public WfTaskQueryRequest candidateGroupIn(List<String> candidateGroupIn) {
    this.candidateGroupIn = candidateGroupIn;
    return this;
  }

  public WfTaskQueryRequest addCandidateGroupInItem(String candidateGroupInItem) {
    this.candidateGroupIn.add(candidateGroupInItem);
    return this;
  }

   /**
   * 候选组集合)
   * @return candidateGroupIn
  **/
  @ApiModelProperty(example = "null", value = "候选组集合)")
  public List<String> getCandidateGroupIn() {
    return candidateGroupIn;
  }

  public void setCandidateGroupIn(List<String> candidateGroupIn) {
    this.candidateGroupIn = candidateGroupIn;
  }

  public WfTaskQueryRequest candidateOrAssigned(String candidateOrAssigned) {
    this.candidateOrAssigned = candidateOrAssigned;
    return this;
  }

   /**
   * 候选人或处理人)
   * @return candidateOrAssigned
  **/
  @ApiModelProperty(example = "null", value = "候选人或处理人)")
  public String getCandidateOrAssigned() {
    return candidateOrAssigned;
  }

  public void setCandidateOrAssigned(String candidateOrAssigned) {
    this.candidateOrAssigned = candidateOrAssigned;
  }

  public WfTaskQueryRequest involvedUser(String involvedUser) {
    this.involvedUser = involvedUser;
    return this;
  }

   /**
   * 流程参与者(处理人、候选人、所有者)
   * @return involvedUser
  **/
  @ApiModelProperty(example = "null", value = "流程参与者(处理人、候选人、所有者)")
  public String getInvolvedUser() {
    return involvedUser;
  }

  public void setInvolvedUser(String involvedUser) {
    this.involvedUser = involvedUser;
  }

  public WfTaskQueryRequest processInstanceId(String processInstanceId) {
    this.processInstanceId = processInstanceId;
    return this;
  }

   /**
   * 任务所在流程实例id
   * @return processInstanceId
  **/
  @ApiModelProperty(example = "null", value = "任务所在流程实例id")
  public String getProcessInstanceId() {
    return processInstanceId;
  }

  public void setProcessInstanceId(String processInstanceId) {
    this.processInstanceId = processInstanceId;
  }

  public WfTaskQueryRequest processInstanceBusinessKey(String processInstanceBusinessKey) {
    this.processInstanceBusinessKey = processInstanceBusinessKey;
    return this;
  }

   /**
   * 任务的业务主键
   * @return processInstanceBusinessKey
  **/
  @ApiModelProperty(example = "null", value = "任务的业务主键")
  public String getProcessInstanceBusinessKey() {
    return processInstanceBusinessKey;
  }

  public void setProcessInstanceBusinessKey(String processInstanceBusinessKey) {
    this.processInstanceBusinessKey = processInstanceBusinessKey;
  }

  public WfTaskQueryRequest processInstanceBusinessKeyLike(String processInstanceBusinessKeyLike) {
    this.processInstanceBusinessKeyLike = processInstanceBusinessKeyLike;
    return this;
  }

   /**
   * 任务的业务主键模糊条件
   * @return processInstanceBusinessKeyLike
  **/
  @ApiModelProperty(example = "null", value = "任务的业务主键模糊条件")
  public String getProcessInstanceBusinessKeyLike() {
    return processInstanceBusinessKeyLike;
  }

  public void setProcessInstanceBusinessKeyLike(String processInstanceBusinessKeyLike) {
    this.processInstanceBusinessKeyLike = processInstanceBusinessKeyLike;
  }

  public WfTaskQueryRequest processDefinitionKey(String processDefinitionKey) {
    this.processDefinitionKey = processDefinitionKey;
    return this;
  }

   /**
   * 任务所在流程定义key
   * @return processDefinitionKey
  **/
  @ApiModelProperty(example = "null", value = "任务所在流程定义key")
  public String getProcessDefinitionKey() {
    return processDefinitionKey;
  }

  public void setProcessDefinitionKey(String processDefinitionKey) {
    this.processDefinitionKey = processDefinitionKey;
  }

  public WfTaskQueryRequest processDefinitionName(String processDefinitionName) {
    this.processDefinitionName = processDefinitionName;
    return this;
  }

   /**
   * 任务所在流程定义名称
   * @return processDefinitionName
  **/
  @ApiModelProperty(example = "null", value = "任务所在流程定义名称")
  public String getProcessDefinitionName() {
    return processDefinitionName;
  }

  public void setProcessDefinitionName(String processDefinitionName) {
    this.processDefinitionName = processDefinitionName;
  }

  public WfTaskQueryRequest processDefinitionKeyLike(String processDefinitionKeyLike) {
    this.processDefinitionKeyLike = processDefinitionKeyLike;
    return this;
  }

   /**
   * 任务所在流程定义key模糊条件
   * @return processDefinitionKeyLike
  **/
  @ApiModelProperty(example = "null", value = "任务所在流程定义key模糊条件")
  public String getProcessDefinitionKeyLike() {
    return processDefinitionKeyLike;
  }

  public void setProcessDefinitionKeyLike(String processDefinitionKeyLike) {
    this.processDefinitionKeyLike = processDefinitionKeyLike;
  }

  public WfTaskQueryRequest processDefinitionNameLike(String processDefinitionNameLike) {
    this.processDefinitionNameLike = processDefinitionNameLike;
    return this;
  }

   /**
   * 任务所在流程定义名称模糊条件
   * @return processDefinitionNameLike
  **/
  @ApiModelProperty(example = "null", value = "任务所在流程定义名称模糊条件")
  public String getProcessDefinitionNameLike() {
    return processDefinitionNameLike;
  }

  public void setProcessDefinitionNameLike(String processDefinitionNameLike) {
    this.processDefinitionNameLike = processDefinitionNameLike;
  }

  public WfTaskQueryRequest executionId(String executionId) {
    this.executionId = executionId;
    return this;
  }

   /**
   * 任务执行id
   * @return executionId
  **/
  @ApiModelProperty(example = "null", value = "任务执行id")
  public String getExecutionId() {
    return executionId;
  }

  public void setExecutionId(String executionId) {
    this.executionId = executionId;
  }

  public WfTaskQueryRequest createdOn(Date createdOn) {
    this.createdOn = createdOn;
    return this;
  }

   /**
   * 任务创建时间
   * @return createdOn
  **/
  @ApiModelProperty(example = "null", value = "任务创建时间")
  public Date getCreatedOn() {
    return createdOn;
  }

  public void setCreatedOn(Date createdOn) {
    this.createdOn = createdOn;
  }

  public WfTaskQueryRequest createdBefore(Date createdBefore) {
    this.createdBefore = createdBefore;
    return this;
  }

   /**
   * 任务创建时间下区间条件
   * @return createdBefore
  **/
  @ApiModelProperty(example = "null", value = "任务创建时间下区间条件")
  public Date getCreatedBefore() {
    return createdBefore;
  }

  public void setCreatedBefore(Date createdBefore) {
    this.createdBefore = createdBefore;
  }

  public WfTaskQueryRequest createdAfter(Date createdAfter) {
    this.createdAfter = createdAfter;
    return this;
  }

   /**
   * 任务创建时间上区间条件
   * @return createdAfter
  **/
  @ApiModelProperty(example = "null", value = "任务创建时间上区间条件")
  public Date getCreatedAfter() {
    return createdAfter;
  }

  public void setCreatedAfter(Date createdAfter) {
    this.createdAfter = createdAfter;
  }

  public WfTaskQueryRequest excludeSubTasks(Boolean excludeSubTasks) {
    this.excludeSubTasks = excludeSubTasks;
    return this;
  }

   /**
   * 是否排除有子任务
   * @return excludeSubTasks
  **/
  @ApiModelProperty(example = "null", value = "是否排除有子任务")
  public Boolean getExcludeSubTasks() {
    return excludeSubTasks;
  }

  public void setExcludeSubTasks(Boolean excludeSubTasks) {
    this.excludeSubTasks = excludeSubTasks;
  }

  public WfTaskQueryRequest taskDefinitionKey(String taskDefinitionKey) {
    this.taskDefinitionKey = taskDefinitionKey;
    return this;
  }

   /**
   * 任务所在环节key
   * @return taskDefinitionKey
  **/
  @ApiModelProperty(example = "null", value = "任务所在环节key")
  public String getTaskDefinitionKey() {
    return taskDefinitionKey;
  }

  public void setTaskDefinitionKey(String taskDefinitionKey) {
    this.taskDefinitionKey = taskDefinitionKey;
  }

  public WfTaskQueryRequest taskDefinitionKeyLike(String taskDefinitionKeyLike) {
    this.taskDefinitionKeyLike = taskDefinitionKeyLike;
    return this;
  }

   /**
   * 任务所在环节key模糊条件
   * @return taskDefinitionKeyLike
  **/
  @ApiModelProperty(example = "null", value = "任务所在环节key模糊条件")
  public String getTaskDefinitionKeyLike() {
    return taskDefinitionKeyLike;
  }

  public void setTaskDefinitionKeyLike(String taskDefinitionKeyLike) {
    this.taskDefinitionKeyLike = taskDefinitionKeyLike;
  }

  public WfTaskQueryRequest dueDate(Date dueDate) {
    this.dueDate = dueDate;
    return this;
  }

   /**
   * 任务过期时间
   * @return dueDate
  **/
  @ApiModelProperty(example = "null", value = "任务过期时间")
  public Date getDueDate() {
    return dueDate;
  }

  public void setDueDate(Date dueDate) {
    this.dueDate = dueDate;
  }

  public WfTaskQueryRequest dueBefore(Date dueBefore) {
    this.dueBefore = dueBefore;
    return this;
  }

   /**
   * 过期时间范围下区间
   * @return dueBefore
  **/
  @ApiModelProperty(example = "null", value = "过期时间范围下区间")
  public Date getDueBefore() {
    return dueBefore;
  }

  public void setDueBefore(Date dueBefore) {
    this.dueBefore = dueBefore;
  }

  public WfTaskQueryRequest dueAfter(Date dueAfter) {
    this.dueAfter = dueAfter;
    return this;
  }

   /**
   * 过期时间范围上区间
   * @return dueAfter
  **/
  @ApiModelProperty(example = "null", value = "过期时间范围上区间")
  public Date getDueAfter() {
    return dueAfter;
  }

  public void setDueAfter(Date dueAfter) {
    this.dueAfter = dueAfter;
  }

  public WfTaskQueryRequest withoutDueDate(Boolean withoutDueDate) {
    this.withoutDueDate = withoutDueDate;
    return this;
  }

   /**
   * 忽略过期时间条件
   * @return withoutDueDate
  **/
  @ApiModelProperty(example = "null", value = "忽略过期时间条件")
  public Boolean getWithoutDueDate() {
    return withoutDueDate;
  }

  public void setWithoutDueDate(Boolean withoutDueDate) {
    this.withoutDueDate = withoutDueDate;
  }

  public WfTaskQueryRequest active(Boolean active) {
    this.active = active;
    return this;
  }

   /**
   * 是否活动
   * @return active
  **/
  @ApiModelProperty(example = "null", value = "是否活动")
  public Boolean getActive() {
    return active;
  }

  public void setActive(Boolean active) {
    this.active = active;
  }

  public WfTaskQueryRequest includeTaskLocalVariables(Boolean includeTaskLocalVariables) {
    this.includeTaskLocalVariables = includeTaskLocalVariables;
    return this;
  }

   /**
   * 是否只查询包含流程环节变量任务
   * @return includeTaskLocalVariables
  **/
  @ApiModelProperty(example = "null", value = "是否只查询包含流程环节变量任务")
  public Boolean getIncludeTaskLocalVariables() {
    return includeTaskLocalVariables;
  }

  public void setIncludeTaskLocalVariables(Boolean includeTaskLocalVariables) {
    this.includeTaskLocalVariables = includeTaskLocalVariables;
  }

  public WfTaskQueryRequest includeProcessVariables(Boolean includeProcessVariables) {
    this.includeProcessVariables = includeProcessVariables;
    return this;
  }

   /**
   * 是否只查询包含流程环节变量和全局变量任务
   * @return includeProcessVariables
  **/
  @ApiModelProperty(example = "null", value = "是否只查询包含流程环节变量和全局变量任务")
  public Boolean getIncludeProcessVariables() {
    return includeProcessVariables;
  }

  public void setIncludeProcessVariables(Boolean includeProcessVariables) {
    this.includeProcessVariables = includeProcessVariables;
  }

  public WfTaskQueryRequest tenantId(String tenantId) {
    this.tenantId = tenantId;
    return this;
  }

   /**
   * 租户
   * @return tenantId
  **/
  @ApiModelProperty(example = "null", value = "租户")
  public String getTenantId() {
    return tenantId;
  }

  public void setTenantId(String tenantId) {
    this.tenantId = tenantId;
  }

  public WfTaskQueryRequest tenantIdLike(String tenantIdLike) {
    this.tenantIdLike = tenantIdLike;
    return this;
  }

   /**
   * 租户模糊条件
   * @return tenantIdLike
  **/
  @ApiModelProperty(example = "null", value = "租户模糊条件")
  public String getTenantIdLike() {
    return tenantIdLike;
  }

  public void setTenantIdLike(String tenantIdLike) {
    this.tenantIdLike = tenantIdLike;
  }

  public WfTaskQueryRequest withoutTenantId(Boolean withoutTenantId) {
    this.withoutTenantId = withoutTenantId;
    return this;
  }

   /**
   * 忽略租户条件
   * @return withoutTenantId
  **/
  @ApiModelProperty(example = "null", value = "忽略租户条件")
  public Boolean getWithoutTenantId() {
    return withoutTenantId;
  }

  public void setWithoutTenantId(Boolean withoutTenantId) {
    this.withoutTenantId = withoutTenantId;
  }

  public WfTaskQueryRequest taskVariables(List<WfQueryVariable> taskVariables) {
    this.taskVariables = taskVariables;
    return this;
  }

  public WfTaskQueryRequest addTaskVariablesItem(WfQueryVariable taskVariablesItem) {
    this.taskVariables.add(taskVariablesItem);
    return this;
  }

   /**
   * 任务变量条件(LOCAL)
   * @return taskVariables
  **/
  @ApiModelProperty(example = "null", value = "任务变量条件(LOCAL)")
  public List<WfQueryVariable> getTaskVariables() {
    return taskVariables;
  }

  public void setTaskVariables(List<WfQueryVariable> taskVariables) {
    this.taskVariables = taskVariables;
  }

  public WfTaskQueryRequest processInstanceVariables(List<WfQueryVariable> processInstanceVariables) {
    this.processInstanceVariables = processInstanceVariables;
    return this;
  }

  public WfTaskQueryRequest addProcessInstanceVariablesItem(WfQueryVariable processInstanceVariablesItem) {
    this.processInstanceVariables.add(processInstanceVariablesItem);
    return this;
  }

   /**
   * 任务所在流程变量条件(GLOBAL)
   * @return processInstanceVariables
  **/
  @ApiModelProperty(example = "null", value = "任务所在流程变量条件(GLOBAL)")
  public List<WfQueryVariable> getProcessInstanceVariables() {
    return processInstanceVariables;
  }

  public void setProcessInstanceVariables(List<WfQueryVariable> processInstanceVariables) {
    this.processInstanceVariables = processInstanceVariables;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WfTaskQueryRequest wfTaskQueryRequest = (WfTaskQueryRequest) o;
    return Objects.equals(this.start, wfTaskQueryRequest.start) &&
        Objects.equals(this.size, wfTaskQueryRequest.size) &&
        Objects.equals(this.sort, wfTaskQueryRequest.sort) &&
        Objects.equals(this.order, wfTaskQueryRequest.order) &&
        Objects.equals(this.name, wfTaskQueryRequest.name) &&
        Objects.equals(this.nameLike, wfTaskQueryRequest.nameLike) &&
        Objects.equals(this.description, wfTaskQueryRequest.description) &&
        Objects.equals(this.descriptionLike, wfTaskQueryRequest.descriptionLike) &&
        Objects.equals(this.priority, wfTaskQueryRequest.priority) &&
        Objects.equals(this.minimumPriority, wfTaskQueryRequest.minimumPriority) &&
        Objects.equals(this.maximumPriority, wfTaskQueryRequest.maximumPriority) &&
        Objects.equals(this.assignee, wfTaskQueryRequest.assignee) &&
        Objects.equals(this.assigneeLike, wfTaskQueryRequest.assigneeLike) &&
        Objects.equals(this.owner, wfTaskQueryRequest.owner) &&
        Objects.equals(this.ownerLike, wfTaskQueryRequest.ownerLike) &&
        Objects.equals(this.unassigned, wfTaskQueryRequest.unassigned) &&
        Objects.equals(this.delegationState, wfTaskQueryRequest.delegationState) &&
        Objects.equals(this.candidateUser, wfTaskQueryRequest.candidateUser) &&
        Objects.equals(this.candidateGroupIn, wfTaskQueryRequest.candidateGroupIn) &&
        Objects.equals(this.candidateOrAssigned, wfTaskQueryRequest.candidateOrAssigned) &&
        Objects.equals(this.involvedUser, wfTaskQueryRequest.involvedUser) &&
        Objects.equals(this.processInstanceId, wfTaskQueryRequest.processInstanceId) &&
        Objects.equals(this.processInstanceBusinessKey, wfTaskQueryRequest.processInstanceBusinessKey) &&
        Objects.equals(this.processInstanceBusinessKeyLike, wfTaskQueryRequest.processInstanceBusinessKeyLike) &&
        Objects.equals(this.processDefinitionKey, wfTaskQueryRequest.processDefinitionKey) &&
        Objects.equals(this.processDefinitionName, wfTaskQueryRequest.processDefinitionName) &&
        Objects.equals(this.processDefinitionKeyLike, wfTaskQueryRequest.processDefinitionKeyLike) &&
        Objects.equals(this.processDefinitionNameLike, wfTaskQueryRequest.processDefinitionNameLike) &&
        Objects.equals(this.executionId, wfTaskQueryRequest.executionId) &&
        Objects.equals(this.createdOn, wfTaskQueryRequest.createdOn) &&
        Objects.equals(this.createdBefore, wfTaskQueryRequest.createdBefore) &&
        Objects.equals(this.createdAfter, wfTaskQueryRequest.createdAfter) &&
        Objects.equals(this.excludeSubTasks, wfTaskQueryRequest.excludeSubTasks) &&
        Objects.equals(this.taskDefinitionKey, wfTaskQueryRequest.taskDefinitionKey) &&
        Objects.equals(this.taskDefinitionKeyLike, wfTaskQueryRequest.taskDefinitionKeyLike) &&
        Objects.equals(this.dueDate, wfTaskQueryRequest.dueDate) &&
        Objects.equals(this.dueBefore, wfTaskQueryRequest.dueBefore) &&
        Objects.equals(this.dueAfter, wfTaskQueryRequest.dueAfter) &&
        Objects.equals(this.withoutDueDate, wfTaskQueryRequest.withoutDueDate) &&
        Objects.equals(this.active, wfTaskQueryRequest.active) &&
        Objects.equals(this.includeTaskLocalVariables, wfTaskQueryRequest.includeTaskLocalVariables) &&
        Objects.equals(this.includeProcessVariables, wfTaskQueryRequest.includeProcessVariables) &&
        Objects.equals(this.tenantId, wfTaskQueryRequest.tenantId) &&
        Objects.equals(this.tenantIdLike, wfTaskQueryRequest.tenantIdLike) &&
        Objects.equals(this.withoutTenantId, wfTaskQueryRequest.withoutTenantId) &&
        Objects.equals(this.taskVariables, wfTaskQueryRequest.taskVariables) &&
        Objects.equals(this.processInstanceVariables, wfTaskQueryRequest.processInstanceVariables);
  }

  @Override
  public int hashCode() {
    return Objects.hash(start, size, sort, order, name, nameLike, description, descriptionLike, priority, minimumPriority, maximumPriority, assignee, assigneeLike, owner, ownerLike, unassigned, delegationState, candidateUser, candidateGroupIn, candidateOrAssigned, involvedUser, processInstanceId, processInstanceBusinessKey, processInstanceBusinessKeyLike, processDefinitionKey, processDefinitionName, processDefinitionKeyLike, processDefinitionNameLike, executionId, createdOn, createdBefore, createdAfter, excludeSubTasks, taskDefinitionKey, taskDefinitionKeyLike, dueDate, dueBefore, dueAfter, withoutDueDate, active, includeTaskLocalVariables, includeProcessVariables, tenantId, tenantIdLike, withoutTenantId, taskVariables, processInstanceVariables);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WfTaskQueryRequest {\n");
    
    sb.append("    start: ").append(toIndentedString(start)).append("\n");
    sb.append("    size: ").append(toIndentedString(size)).append("\n");
    sb.append("    sort: ").append(toIndentedString(sort)).append("\n");
    sb.append("    order: ").append(toIndentedString(order)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    nameLike: ").append(toIndentedString(nameLike)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    descriptionLike: ").append(toIndentedString(descriptionLike)).append("\n");
    sb.append("    priority: ").append(toIndentedString(priority)).append("\n");
    sb.append("    minimumPriority: ").append(toIndentedString(minimumPriority)).append("\n");
    sb.append("    maximumPriority: ").append(toIndentedString(maximumPriority)).append("\n");
    sb.append("    assignee: ").append(toIndentedString(assignee)).append("\n");
    sb.append("    assigneeLike: ").append(toIndentedString(assigneeLike)).append("\n");
    sb.append("    owner: ").append(toIndentedString(owner)).append("\n");
    sb.append("    ownerLike: ").append(toIndentedString(ownerLike)).append("\n");
    sb.append("    unassigned: ").append(toIndentedString(unassigned)).append("\n");
    sb.append("    delegationState: ").append(toIndentedString(delegationState)).append("\n");
    sb.append("    candidateUser: ").append(toIndentedString(candidateUser)).append("\n");
    sb.append("    candidateGroupIn: ").append(toIndentedString(candidateGroupIn)).append("\n");
    sb.append("    candidateOrAssigned: ").append(toIndentedString(candidateOrAssigned)).append("\n");
    sb.append("    involvedUser: ").append(toIndentedString(involvedUser)).append("\n");
    sb.append("    processInstanceId: ").append(toIndentedString(processInstanceId)).append("\n");
    sb.append("    processInstanceBusinessKey: ").append(toIndentedString(processInstanceBusinessKey)).append("\n");
    sb.append("    processInstanceBusinessKeyLike: ").append(toIndentedString(processInstanceBusinessKeyLike)).append("\n");
    sb.append("    processDefinitionKey: ").append(toIndentedString(processDefinitionKey)).append("\n");
    sb.append("    processDefinitionName: ").append(toIndentedString(processDefinitionName)).append("\n");
    sb.append("    processDefinitionKeyLike: ").append(toIndentedString(processDefinitionKeyLike)).append("\n");
    sb.append("    processDefinitionNameLike: ").append(toIndentedString(processDefinitionNameLike)).append("\n");
    sb.append("    executionId: ").append(toIndentedString(executionId)).append("\n");
    sb.append("    createdOn: ").append(toIndentedString(createdOn)).append("\n");
    sb.append("    createdBefore: ").append(toIndentedString(createdBefore)).append("\n");
    sb.append("    createdAfter: ").append(toIndentedString(createdAfter)).append("\n");
    sb.append("    excludeSubTasks: ").append(toIndentedString(excludeSubTasks)).append("\n");
    sb.append("    taskDefinitionKey: ").append(toIndentedString(taskDefinitionKey)).append("\n");
    sb.append("    taskDefinitionKeyLike: ").append(toIndentedString(taskDefinitionKeyLike)).append("\n");
    sb.append("    dueDate: ").append(toIndentedString(dueDate)).append("\n");
    sb.append("    dueBefore: ").append(toIndentedString(dueBefore)).append("\n");
    sb.append("    dueAfter: ").append(toIndentedString(dueAfter)).append("\n");
    sb.append("    withoutDueDate: ").append(toIndentedString(withoutDueDate)).append("\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    includeTaskLocalVariables: ").append(toIndentedString(includeTaskLocalVariables)).append("\n");
    sb.append("    includeProcessVariables: ").append(toIndentedString(includeProcessVariables)).append("\n");
    sb.append("    tenantId: ").append(toIndentedString(tenantId)).append("\n");
    sb.append("    tenantIdLike: ").append(toIndentedString(tenantIdLike)).append("\n");
    sb.append("    withoutTenantId: ").append(toIndentedString(withoutTenantId)).append("\n");
    sb.append("    taskVariables: ").append(toIndentedString(taskVariables)).append("\n");
    sb.append("    processInstanceVariables: ").append(toIndentedString(processInstanceVariables)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

